- src/main/java/oss/fosslight/util/FileUtil.java
Fix a bug to create nvd directories.
- An error occurs when creating related folders during NVD Data Sync.
```
ERROR [NvdDataService.java, executeNvdDataSync():64] - /data/fosslight/nvd/cve/nvdcpematch-1.0.json.zip (No such file or directory)
java.io.FileNotFoundException: /data/fosslight/nvd/cve/nvdcpematch-1.0.json.zip (No such file or directory)
at java.io.FileOutputStream.open0(Native Method)
at java.io.FileOutputStream.open(FileOutputStream.java:270)
at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
at oss.fosslight.util.FileUtil.downloadFile(FileUtil.java:325)
at oss.fosslight.service.NvdDataService.nvdFeedDataDownloadJob(NvdDataService.java:437)
at oss.fosslight.service.NvdDataService.executeNvdDataSync(NvdDat …
```
> Fix a bug to create directories

- src/main/java/oss/fosslight/scheduler/SchedulerWorkerTask.java
- src/main/java/oss/fosslight/service/NvdDataService.java
* Remove the warning message "Field 'log' already exists."
* Delete ```@slf4j``` Annotation in SchedulerWorkerTask.java, NvdDataService.java
* Delete ```import lombok.extern.slf4j.slf4j;```
> Remove warning message

- .gitignore
docker-compose automatically generate db/data folder(for mariadb) and web-data folder(for web).
That folders are unreleated to project because They are personal data.
So add folders name to .gitignore
- Issue number #30 
> Update .gitignore to ignore personal data folders

- src/main/java/oss/fosslight/CoTopComponent.java
Signed-off-by: ubermen5che <ubermen5ch1308@gmail.com>
Fix typo in CoTopComponent.java
---
`String encordedFilename`
`String encodedFilename`
> Fix typo in CoTopComponent.java in fosslight

- docker-compose.yml
Signed-off-by: YoungHo Choi <0505zxc@gmail.com>
- Docker use default timezone from UTC. so I fixed timezone to Asia/Seoul like timezone of db container.
> Fix Timezone to Asia/Seoul

- src/main/webapp/WEB-INF/views/admin/license/list-js.jsp
- src/main/webapp/WEB-INF/views/admin/license/list.jsp
- src/main/webapp/WEB-INF/views/admin/oss/list.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/viewpopup.jsp
- Fix Typo 'WebSite' to 'Website' in listSearch field.
- Fix Typo 'Web site' to 'Website' in list column name.
> FIx typo 'website' in UI

- .github/workflows/pull-request.yml
* Save docker-compose log as docker-compose-web.log and docker-compose-db.log respectively.
* It shows the saved log file in the final step of github actions.
* add Save docker-compose logs sequence
* add Show db container log sequence
* add Show web container log sequence
* https://github.com/fosslight/fosslight/runs/3309800143?check_suite_focus=true
* https://stackoverflow.com/questions/35414495/save-docker-compose-logs-to-a-file
> Add to show docker-compose log in github-actions

- src/main/resources/oss/fosslight/repository/OssMapper.xml
- src/main/webapp/WEB-INF/views/admin/oss/list.jsp
Add License Type option for OSS List search
1. Add License Type select box in list.jsp
2.  Add AND operator clause for License Type in OssMapper.xml
> Add License Type option for OSS List search

- src/main/webapp/WEB-INF/views/admin/project/verification.jsp
Signed-off-by: jongun.chae <cha452jg@gmail.com>
Hide a save button for a normal user in packaging tab. Admin, watcher, and creator only can see the button.
> Expose a save button for a creator, watcher, and admin

- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
Signed-off-by: hyewoncc <hyewoncc@gmail.com>
In Project - SRC/BIN tabs, 'Check OSS Name' button is only shown to Admin, Watcher and Creator.
Other unrelated users couldn't see it now. 
> Fix hide 'Check OSS Name' button from unrelated users

- db/initdb.d/fosslight_create.sql
- src/main/java/oss/fosslight/domain/ProjectIdentification.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
1. Now fosslight supports 6 open source package repositories (GitHub, Maven, PyPI, npm). To support two additional open source package repositories (Pub, CocoaPods), Modified fosslight_create.sql, OssServiceImpl::checkOssName, and OssServiceImpl::saveOssCheckName as follows.
2. And fosslight recommends an oss name by checking the oss list.
If the download location is not stored in the OSS List only for the OSS Name that is an Unconfirmed Open Source Warning message, recommend the OSS Name according to the OSS Naming Rule.
So in Project List > SRC tab, As shown in the picture below, Suppose that there is an open source specified in the downloadlocation for a specific repository and 'Unconfirmed Open Source' warning message is appeared.
If opensource's download location is specified in 6 …
> Enhancement function : Recommend the OSS Name according to the OSS Naming Rule

- db/initdb.d/fosslight_create.sql
- Delete Need check in the Obligation Type from the search box in the License List.
- Need Checks's option number is 90. so I hide option with a value of 90 after rendering.  
##ScreenShot
> Delete "Need check" in the Obligation Type from the search box in the License List

- CHANGELOG.md
- db/initdb.d/fosslight_create.sql
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/repository/CodeMapper.java
- src/main/java/oss/fosslight/repository/NvdDataMapper.java
- src/main/java/oss/fosslight/service/NvdDataService.java
- src/main/resources/oss/fosslight/repository/CodeMapper.xml
- src/main/resources/oss/fosslight/repository/NvdDataMapper.xml
Add logic to register all data from 2002 to NVD Feed Data during initial setting.
1. How it works
- When the value of common code System initialize flag (Code management Number: 990) > Detail Code No :100 (NVD Data Feed initialize flag) is “Y”, data initialization is performed.
- The default value is set to "N", and if the user changes it to "Y", all NVD-related Data is cleaned during the next NVD schedule operation and registered sequentially from the 2002 data file.
2. How to apply
- Add 990 code to fosslight_create.sql. In case of new configuration, 990 code is registered. ( Default "N" )
- How to add initialization handling to a pre-configured system : 
-  Add code 990 to DB and apply after merging source code (5 Files)
-  Initialization is included when working with NVD Batch at …
> Add function to save NVD Feed Data from 2002

- src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
* Add a condition when length == 1.
* When length == 1 "At least two OSS versions are required." alert
| oss.length == 1 | oss.length > 1 |
|:--:|:--:|
|alert|popup|
|![스크린샷 2021-09-15 오후 12 47 21](https://user-images.githubusercontent.com/32615702/133367476-74db9ecc-bd7f-4b12-af8b-a491d15bbc85.png)|![스크린샷 2021-09-15 오후 12 28 08](https://user-images.githubusercontent.com/32615702/133365899-043740be-946f-4504-a421-3a0aa061e8f0.png)|
> Add alert when the number of OSS versions is 1

- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
- src/main/resources/template/notice/notice.txt
- src/main/resources/template/notice/notice_sks.txt
Signed-off-by: mhjang <mhjang@miridih.com>
When you download an OSS Notice file in a .txt type, this adds a line separator between the notice introduction and the OSS list that will be packaged.
> Add Line Separator Between Notice Intro And OSS Lists

- docker-compose.yml
* docker-compose unquoted port mapping may be interpreted as a base-60 value
* 25:25 -> '25:25'
> https://docs.docker.com/compose/compose-file/compose-file-v3/#ports
Note
When mapping ports in the HOST:CONTAINER format, you may experience erroneous results when using a container port lower than 60, because YAML parses numbers in the format xx:yy as a base-60 value. For this reason, **_we recommend always explicitly specifying your port mappings as strings._**
> unquoted port mapping may be interpreted as a base-60 value

- db/initdb.d/fosslight_create.sql
- src/main/java/oss/fosslight/common/CoConstDef.java
- src/main/java/oss/fosslight/service/impl/SystemConfigurationServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/system/configuration-js.jsp
- src/main/webapp/WEB-INF/views/admin/system/configuration.jsp
* add External System related code
* CD_EXTERNAL_SERVICE_SERVICE_USED_FLAG (914)
* CD_EXTERNAL_SERVICE_SETTING (930)
* CD_DTL_GITHUB_TOKEN (100)
* encrypt the token value and store it in the db
* add External Service Settings tab to Configuration page
* set the token value to not be visible on the Configuration page
> Add External Service settings to the configuration page

- .github/PULL_REQUEST_TEMPLATE.md
- Dockerfile
- docker-compose.yml
Add template to docker environment.
- When running with docker, an error related to export occurs. This is caused by not finding the template file.
> Add template to docker environment

- src/main/webapp/WEB-INF/views/admin/license/edit.jsp
- The nickname input width size to double
| capture
| -- 
|  
| ![image](https://user-images.githubusercontent.com/17478634/135771832-5728bdeb-2fb9-4a9c-ade4-da9fcf19ecdd.png)
> Fix the nickname input width size to double

- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/resources/template/email/projectInfo.html
- src/main/resources/template/email/vulnerabilityInfo.html
Signed-off-by: Youn-Sung Hwang <acafela91@gmail.com>
- In the Velocity template, there was a code duplication that changed the CVE-ID to a link,
so i added the method to CommonFunction and put it to VelocityContext.
> Change CVE-ID to a link (#212)

- src/main/java/oss/fosslight/domain/OssMaster.java
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- src/main/resources/static/css/commonIframe.css
- src/main/webapp/WEB-INF/views/admin/oss/list-js.jsp
- src/main/webapp/WEB-INF/views/admin/oss/list.jsp
Before there was no OSS type search in OSS list.
After modification, there is OSS type search in OSS list.
Fixes #165
Resolves #165 .
**Note : After modification, the size of img_icon.png is reduced in 8KB. Is it OK??**
> Add OSS ​​Type to search condition in OSS List

- src/main/java/oss/fosslight/common/CoCodeManager.java
Before modification, There's possibility to occur null pointer
exception. After modification, There is not possibility to occur
null pointer exception.
Signed-off-by: yugeeklab yugeeklab@gmail.com
> Fix NPE in common/CoCodeManager

- build.gradle
* update spdx/tools-java (1.0.2 -> 1,0.3)
Resolves #189 (download location regex error), #148 (Possibly ambiguous ID being introduced warning message)
> Update spdx/tools-java version

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/domain/BinaryMaster.java
- src/main/java/oss/fosslight/domain/CodeBean.java
- src/main/java/oss/fosslight/domain/ComBean.java
- src/main/java/oss/fosslight/domain/File.java
- src/main/java/oss/fosslight/domain/LicenseMaster.java
- src/main/java/oss/fosslight/domain/OssMaster.java
- src/main/java/oss/fosslight/domain/PartnerMaster.java
- src/main/java/oss/fosslight/domain/Project.java
- src/main/java/oss/fosslight/domain/ReportCombean.java
- src/main/java/oss/fosslight/repository/OssMapper.java
- src/main/java/oss/fosslight/service/OssService.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- Update OSS Sync Function to shorten the time to save during OSS sync.
- In the part of OSS Sync processing, the part that retrieves OSS information does not refer to memory, but change it so that it is fetched directly from the DB.
-  Delete all refreshOssInfo() calls in loop.
- Fix the vulnerability that public array is assigned to private variable.
> Shorten the time required to save during OSS sync

- src/main/webapp/WEB-INF/views/admin/oss/viewpopup.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
- In the OSS version-specific information popup that appears when you click a cell in the ID column of the OSS Table, if you are an admin, show a list of comments.
- Like a project or 3rd party, even for self-check, open a popup of OSS version-specific information that appears when you click a cell in the ID column of the OSS table.
> Update OSS Table > view comment info of oss popup

- src/main/java/oss/fosslight/util/ExcelUtil.java
Signed-off-by: Taehyun <kimtaehyun98@naver.com>
- test file : [FOSSLight-Report_test_License.xlsx](https://github.com/fosslight/fosslight/files/7502802/FOSSLight-Report_test_License.xlsx)
- test file : [SPDX_test_License_comments.xls](https://github.com/fosslight/fosslight/files/7502809/SPDX_test_License_comments.xls)
> SPDX Spreadsheet License List parsing

- src/main/java/oss/fosslight/controller/PartnerController.java
- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/java/oss/fosslight/controller/SPDXDownloadController.java
- src/main/java/oss/fosslight/controller/VerificationController.java
- src/main/java/oss/fosslight/repository/ProjectMapper.java
- src/main/java/oss/fosslight/service/ProjectService.java
- src/main/java/oss/fosslight/service/VerificationService.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
- src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
- src/main/resources/oss/fosslight/repository/PartnerMapper.xml
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
- src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
- src/main/resources/static/css/commonIframe.css
- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
- src/main/webapp/WEB-INF/views/admin/project/edit.jsp
- src/main/webapp/WEB-INF/views/admin/project/verification-js.jsp
- Add a "Create Project for OSS Notice" button for the confirmed 3rd party.
When the corresponding button is clicked, the 3rd party loaded Project is created. At this time, the project is made into Identification confirm state. However, only when it is impossible to confirm the identification, the status of the identification request is made.
- Packaging > Notice tab > Hide OSS Version
After hiding the OSS version, merge the OSS names and issue an OSS Notice.
- Identification tab > admin check
In case of admin check, even if OSS Name is changed to nickname, keep OSS Name written by user.
> Add a function to copy 3rd party to Project

- db/initdb.d/fosslight_create.sql
- src/main/java/oss/fosslight/common/CoConstDef.java
- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/java/oss/fosslight/service/impl/SystemConfigurationServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/system/configuration.jsp
* delete token encryption
* changed to register Github Token in Code Management
```
DELETE FROM T2_CODE_DTL WHERE CD_NO=930;
DELETE FROM T2_CODE WHERE CD_NO=930;
INSERT INTO T2_CODE (CD_NO, CD_NM, CD_EXP, SYS_CD_YN) VALUES ('705', 'External Service Setting', 'System Detail Setting Code', 'N');
INSERT INTO T2_CODE_DTL (`CD_NO`, `CD_DTL_NO`, `CD_DTL_NM`, `CD_SUB_NO`, `CD_DTL_EXP`, `CD_ORDER`, `USE_YN`) VALUES ('705', '100', 'Github Token', '', 'github token', 1, 'Y');
```
> Change github token in code management

- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
* Fix an error where licenses were displayed as duplicates on the Check License page
> Fix the license duplication bug in Check License

- build.gradle
Downgrade the version of spdx-rdf-store for spdx rdf download before changing to java 11.
* tools-java 1.0.3 (not changed)
* spdx-rdf-store 1.0.3 -> 1.0.2 (downgrade)
> Change SPDX dependecy version

- CONTRIBUTING.md
If the contributor does not have permission, the label setting is not possible, so remove the label setting from the contribution guide.
> Remove the label setting for PR from the guide

- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
When leaving a comment in the Check License function, do not print `()` if the OSS version is null.
```
The following Licenses were modified by Check License.
https://github.com/explosion/spaCy WRONG LICENSE 7 => MIT
https://github.com/fosslight/fosslight WRONG LICENSE 1 => AGPL-3.0
https://github.com/fosslight/fosslight_binary_scanner WRONG LICENSE 13 => Apache-2.0
https://github.com/fosslight/fosslight_dependency_scanner WRONG LICENSE 5 => Apache-2.0
https://github.com/fosslight/fosslight_reuse WRONG LICENSE 4 => GPL-3.0
https://github.com/fosslight/fosslight_scanner WRONG LICENSE 11 => Apache-2.0
https://github.com/fosslight/fosslight_scanner_service WRONG LICENSE 12 => Apache-2.0
https://github.com/fosslight/fosslight_source_scanner WRONG LICENSE 9 => Apache-2.0 …
```
> Do not print () if the OSS version is null when leaving a comment in the Check License.

- src/main/java/oss/fosslight/controller/OssController.java
There's a bug that "work" method tried to find deleted ossMaster using "getOssMasterOne" method.
So Null point exception occured in getOssMaster.
I think delete function should be done in the later.
> Eliminate null pointer exception in OSS Controller

- src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
Hi, this is my solution for the issue #341 
The Check License and Check OSS Name buttons did not follow the same display conditions as the Save button.
I changed the display conditions oh these buttons in Identification and Self-check so that now when they are deployed it's because they actually work.
Please let me know if there are any corrections I need to make :)
> Hide the Check License, Check OSS Name buttons with the same conditions as the Save button.

- src/main/java/oss/fosslight/util/ExcelUtil.java
* If the value to be loaded is NONE or NOASSERTION, load in a null space.
* Make it possible to upload SPDX documents as if uploading FOSSLIGHT REPORT to the following Tab.
* Project > SRC, BIN
* 3rd Party
* Self-check
* How to do "Comment Load method.
* AS-IS: Load values read from License Comments
* TO-BE: If there is anything already written in the comment section in License Confused, divide it into / and attach it.
* ex) License Concluded : (MIT OR GPL-2.0), License Comments : This is test
* Comment : (MIT OR GPL-2.0) / This is test
[test.xls](https://github.com/fosslight/fosslight/files/7782493/test.xls)
> License and Comment output when loading SPDX

- src/main/java/oss/fosslight/util/ExcelUtil.java
Separate FOSSLight Report and Commnet load method of SPDX.
- FOSSLight Report : The written comment is loaded into the OSS table as it is.
- SPDX : When the License is Dual or Multi, add the contents of the License to the beginning of the Comment.
* SPDX test file :[spdx spreadsheet](https://github.com/fosslight/fosslight/files/7794950/test.2.xls)
* FOSSLight report file: [oss report](https://github.com/fosslight/fosslight/files/7794951/test.xlsx)
> Add comment output when loading SPDX

- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/config/CustomAuthenticationProvider.java
- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/java/oss/fosslight/util/ExcelUtil.java
- Update log error message for LDAP.
- Delete the ColumnMissingException, ColumnNameDuplicateException  error output when reading the OSS Report.
- Fix the bug where the space disappears in the license name when comparing BOM in Project List.
- Fix the bug related to the license type check to be loaded during Auto ID.
> Fix bugs in BOM Compare and Auto ID

- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
- When sending license mail, add a shortcut link to license name.
- In the SRC tab of the project, change the text in the upload field from General Model to FOSSLight Report.
> Add a shortcut link when sending a license email

- src/main/resources/application.properties
> Add a default value for server domain

- CHANGELOG.md
- build.gradle
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/service/OssService.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
Fix the bug where OSS Type is not Dual and not version diff is displayed incorrectly.
- In case of V-Diff when saving a new OSS: When saving the same oss name and different version at the same time, when saving a new one > After collecting the information of the same oss name, the oss type flag value is saved. After collecting the information, the deletion process proceeds before saving the flag value. When this happens, the V-Diff value is stored in the oss type flag value.
- When the OSS Type is different from the saved value when editing: When the same oss name, different version (1.0, 2.0) is modified at a similar point in time > There is a phenomenon in which a flag value different from the license in which the oss type flag value is stored is stored.
> Fix the bug where OSS Type is not Dual and not version diff is displayed incorrectly

- CHANGELOG.md
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
- Fix the bug where OSS rename popup appears even when OSS is newly added.
- Change the message that pops up when OSS is renamed.
> Fix bug where OSS Rename popup appears for new OSS

- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/domain/ProjectIdentification.java
- src/main/java/oss/fosslight/repository/OssMapper.java
- src/main/java/oss/fosslight/service/OssService.java
- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- src/main/resources/static/css/commonIframe.css
- src/main/webapp/WEB-INF/views/admin/project/src-js.jsp
- Fix the bug where the license is not loaded in the OSS details popup that appears when you double-click a row in the OSS Table.
- Fix a bug that occurs when uploading the FOSSLight Report file from the SRC tab.
- When you click Check License, when ClearyDefined returns an error, try one more time. 
- Add exception handling in case of 5** error from ClearyDefined.
- In BAT, remove % from the Percentage Column and modify it so that it can be sorted numerically.
> Fix the bug where the license was not displayed on the OSS details page

- CHANGELOG.md
- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/repository/VerificationMapper.java
- src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
- src/main/java/oss/fosslight/util/FileUtil.java
- src/main/resources/oss/fosslight/repository/VerificationMapper.xml
1. Fix the bug that Copyright is not displayed in OSS Notice.
- Copyright text, Homepage cannot be loaded if identification is confirmed with nickname.
2. Update self-check unclear obligation message display condition.
> Fix the bug that Copyright is not displayed in OSS Notice

- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/java/oss/fosslight/controller/VerificationController.java
- src/main/java/oss/fosslight/domain/Project.java
- src/main/java/oss/fosslight/repository/ProjectMapper.java
- src/main/java/oss/fosslight/service/VerificationService.java
- src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
Add a function to copy even the status when copying the project.
- In the case of a project whose identification has been confirmed, it is possible to select the status to be copied.
> Add a function to copy even the status when copying the project.

- src/main/java/oss/fosslight/util/ExcelUtil.java
- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
In OSS Bulk, 
- match header columns without case sensitivity.
- do not load if OSS Name or Declared License is null.
Sample file to test: [Sample_upload.xls](https://github.com/fosslight/fosslight/files/8311276/Sample_upload.xls)
- Previous : ![image](https://user-images.githubusercontent.com/4284712/159163950-412b082d-159b-457a-aabd-852c57ec20f7.png)
- Now: ![image](https://user-images.githubusercontent.com/4284712/159163963-288b9a44-ceaa-4b4a-bd16-f923802a0f9e.png)
> Do not load if OSS Name or Declared License is null in OSS Bulk

- docker-compose.yml
adopt [docker-compose Variable substitution](https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution)
Signed-off-by: Bae KwonHan <kwonhan.bae@linecorp.com>
with this change, we can adopt some variables from environment when start service via `docker-compose`
> adopt docker-compose Variable substitution

- CHANGELOG.md
- build.gradle
- src/main/java/oss/fosslight/common/CommonFunction.java
In self-check, a warning message says `Specify OSS Name or put 1 license in a row.`, indicate Obligation with '?'.
- `Specify OSS Name or put 1 license in a row.` is a message displayed when OSS Name is - and multiple licenses are written in one row.
> Change the indication of unclear obligation to OSS Name : -

- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/config/SecurityConfig.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/java/oss/fosslight/service/OssService.java
- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/util/ExcelUtil.java
- src/main/java/oss/fosslight/util/OssComponentUtil.java
- Fix the bug of loading all licenses even though it is a dual license in Check License.
- Fix the bug where the License Type is saved incorrectly when saving OSS.
- Change the mail sender name.
- In case the email name is too long, change it to split it with /.
- Remove the function that automatically fills in Homepage and Download location when uploading OSS Report.
- Fix the bug where the result of changing the license is left in the comment twice when uploading the OSS report.
> Fix the bug of loading all licenses even though it is a dual license in Check License.

- CHANGELOG.md
- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
- Fix the bug where the warning message is not displayed for the deactivated OSS.
- Modify the Check OSS Name to read only before # in the github link.
> Fix the bug where the warning message is not displayed for the deactivated OSS

- src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
Fix a bug where the download location is null when it is displayed as null in the OSS details tab.
> Fix the bug if the download location is null

- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
Change Status Message for Row Registration Failed in OSS Bulk.
- AS-IS: The status message for the row where OSS registration failed is not changed.
- TO-BE : Change the status of the row that has failed OSS registration to `Failed`.
> Change Status Message for Row Registration Failed in OSS Bulk

- CHANGELOG.md
- src/main/java/oss/fosslight/controller/VerificationController.java
- src/main/java/oss/fosslight/domain/Statistics.java
- src/main/java/oss/fosslight/service/impl/StatisticsServiceImpl.java
- src/main/resources/oss/fosslight/repository/BinaryDataHistoryMapper.xml
- src/main/resources/oss/fosslight/repository/CodeMapper.xml
- src/main/resources/oss/fosslight/repository/DashboardMapper.xml
- src/main/resources/oss/fosslight/repository/HistoryMapper.xml
- src/main/resources/oss/fosslight/repository/NoticeMapper.xml
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
- src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
- src/main/resources/oss/fosslight/repository/SentMailMapper.xml
- src/main/resources/oss/fosslight/repository/StatisticsMapper.xml
- src/main/resources/oss/fosslight/repository/T2UserMapper.xml
- src/main/resources/oss/fosslight/repository/VulnerabilityHistoryMapper.xml
- src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
Load the default comments when confirming packaging from the `email default contents` of `Code Management` and include them in the email.
> Add a default comment to the Packaging confirm mail

- src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
> When issuing a Notice in Self-check, load and include the OSS link instead of the Homepage by loading the Download location.
If Unconfirmed OSS OR Unconfirmed version OR OSS Name is -
- AS-IS: Issue OSS Notice with information written on the row.
- Problem: Clicking the OSS name in OSS Notice does not work because there is no Homepage column.
- TO-BE: In this case, print the download location in the Homepage of the OSS Notice.
> When issuing a Notice in Self-check, load and include the OSS link instead of the Homepage by loading the Download location

- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
Signed-off-by: suhwan-cheon <soo7652@naver.com>
- Change the UI for self-check upload (#485)
- when url radio button is disabled
- when url radio button is abled
- I changed the first radio button - onchange method in edit.jsp during the modification, and I am worried about that part.
Because I don't fully understand the code. 😭
- So if you have any problems, please reply! I'll fix it quickly🏃
> Change the UI for self-check upload

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/java/oss/fosslight/service/OssService.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
Use OSS storage logic in OSS Bulk Registration.
- The save OSS function can be used in multiple pages, so move it to the Service.
- Check OSS name and nickname in OSS Bulk.
> Use OSS storage logic in OSS Bulk Registration.

- src/main/webapp/WEB-INF/views/admin/oss/AJAX/ossDetailview.jsp
add function to modify/view oss details information in the oss version information window
step :
identification > select ID column > open new window of the list of oss version information > select "OSS Name" > open the oss details window(admin can edit the information)
oss version information window : 
oss details window
> open oss details window in oss version information

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/service/impl/ApiVulnerabilityServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
- Fix the bug where OSS Name is stored as duplicate.
- Fix bug where CVE-ID is returned as duplicate in API > Vulnerability. (This bug is reproduced when the OSS version is blank.)
> Fix bug where CVE-ID is returned as duplicate in API > Vulnerability.

- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
- src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
- src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
Signed-off-by: Dongwon Kim [freshtuna@kakao.com](mailto:freshtuna@kakao.com)
1. This PR modify reloaded identification tab after 'change license' or 'change nickname' to you're working on
2. This PR remove 'msg.project.entered.first.tab' message. Because the popup doesn't disappear after clicking change button
I think that a behavior (there is a problem of moving to the previous tab after Change License) **is depends on which tab you clicked in Identification column of project**.
Suppose you clicked BOM tab in Identification column. 
1. Identification iframe loaded with BOM tab
3. Change tab to SRC or BIN
4. click 'update OSS name' or 'update OSS license' button, and popup window is created
5. if you  update OSS name or license in popups successfully, it reload Identification tab of BOM …
> Modify reloaded identification tab after 'change license' or 'change nickname' to you're working on.

- db/initdb.d/fosslight_create.sql
- src/main/java/oss/fosslight/common/CoConstDef.java
- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/webapp/WEB-INF/views/admin/license/edit.jsp
If you need to output the url of the license (ex. Simple NOTICE issuance), the website value is output.
However, if this flag is `Y`, the `internal url `is output instead of the license `website`.
> Add a flag to use the license's internal url

- src/main/webapp/WEB-INF/views/admin/system/user-js.jsp
Signed-off-by: Han Min <hm5395@naver.com>
When the value of CD_DTL_EXP is null or Y, the email is hidden.
but I want the email to be hidden Only when CD_DTL_EXP is Y.
I solved the problem using 'ne' function.
so when CD_DTL_EXP is null, admin can see emails.
> Hide user email as per option

- src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
If user hover the mouse over the 'project name' in the 'project list', show tooltip text "Double click"
> Show "Double click" when mouse hovers on project name

- src/main/webapp/WEB-INF/views/admin/selfCheck/AJAX/view.jsp
1. Self-Check List > Add > Version field
- Insert script in the version field
2. When viewing a project details that was added just before
- Script inserted in the version field is executed
- When viewing a project details, script is not excuted. The script is printed as a string.
> XSS prevention with jstl

- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
Signed-off-by: Daeeun Ko <7273322@naver.com>
This PR removes newline in Self-check comment.
If user click the radio button, comment(span.checkSet > label) element's display is changed. But checkSet element(span.checkSet) is still there. And the checkSet elemnet have a padding(padding-right:5px;). It causes unnecessary space.
1. Modify the targets that are changed by radio button. label ➡ .checkSet
2. Move display style(display: none;) label to checkSet
> Fix comment in Self-check to remove newline

- src/main/webapp/WEB-INF/views/admin/oss/list-js.jsp
In the **OSS List**, even if a space is included at the beginning and end of `Homepage`, `OSS Name`, and `License Name`, make it searchable.
If there is a space before or after a word, the search is not performed properly.
https://user-images.githubusercontent.com/33304982/180017622-55ca4555-7c01-4d3c-ae44-c65710ebe227.mp4
I used a function 'trim()' to remove a space before or after a word
https://user-images.githubusercontent.com/33304982/180018497-957fb694-896a-479d-a2e9-cd6899c75846.mp4
> Make it search even if space is included at the beginning and end of the word in the OSS List

- Dockerfile
- db/wait-for
Fix bugs that do not run with docker-compose on Windows. 
- Update [wait-for](https://github.com/eficode/wait-for) to 2.2.3
> Fix bugs that do not run with docker-compose on Windows

- src/main/java/oss/fosslight/validation/custom/T2CoOssValidator.java
- src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
- Remove version diff notification popup when deleting OSS.
- Fix the bug where the "OSS With similar link already exists" message, which compares the Homepage/Download location created in OSS with the one stored in OSS, is displayed even for links that are not similar.
> Remove version diff notification popup when deleting OSS

- src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
3rd Party's Basic Information > Increase the length of the name field. (Realated issue: #460 )
The requirements were:
- In the Watcher column, increase the length of the red box below to the size of the green box.
- Increase the length of the Creator and Reviewer by the red box.
But, I don't know the exact size of the box. 
SoI arbitrarily increased the size of the boxes
> Increase the length of the name field 

- src/main/resources/static/css/commonIframe.css
- src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
The project list shows priority through the background color of Status column.
Red means Priority1, and yellow means Priority2.
However, it was impossible to know the meaning of these colors.
So I added the information of each color in the tooltip.
(Related issue: https://github.com/fosslight/fosslight/issues/581)
> Add priority to the status tooltip of the Project List

- .github/workflows/pull-request.yml
- .github/workflows/release-publish.yml
Issue #605 
I updated workflows to apply **dependency caching**.
Jobs on GitHub-hosted runners start in a clean virtual environment and **must download dependencies each time**, causing increased network utilization, longer runtime, and increased cost. To help speed up the time it takes to recreate files like dependencies, GitHub can cache files that frequently use in workflows.
Java projects can run faster on GitHub Actions by enabling dependency caching on the [setup-java](https://github.com/actions/setup-java) action. `setup-java` supports caching for both Gradle and Maven projects.
The following example enables caching for a Java project with Gradle:
```yaml
steps:
- uses: actions/checkout@v3
- uses: actions/setup-java@v3
with: …
```
> Caching Dependencies to speed up workflows

- src/main/webapp/WEB-INF/views/admin/project/edit.jsp
Signed-off-by: Han Min <hm5395@naver.com>
Requirement:
1. In the Watcher column, increase the length of the red box below to the size of the green box.
2. Increase the length of the Creator and Reviewer by the red box.
I have increased the size of the name field than before.
> Increase the length of the project's name field

- src/main/webapp/WEB-INF/views/template/layout/admin/header.jsp
when user mouse hover over the name at the top of the left menu, show the user's name instead of User Settings.
> Show the user's name, when Mouse hover

- src/main/java/oss/fosslight/service/impl/HistoryServiceImpl.java
Signed-off-by: myway00 <junior0614@naver.com>
#545 
<Before>
- `History List > Modify Type: Open Source > Obligation`  was shown as `000` (default Code type of Obligation) regardless of its type.
<After>
- Obligation Code value is now shown as its type.
> Fix return value to Obligation Type

- src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
- src/main/java/oss/fosslight/common/Url.java
- src/main/java/oss/fosslight/service/ApiProjectService.java
- src/main/java/oss/fosslight/service/impl/ApiProjectServiceImpl.java
- src/main/java/oss/fosslight/util/YamlUtil.java
Add project BOM tab export json to the API.  
Json format is the same as adding Vulnerability to the format of the yaml file.
> Add project bom tab export json to the API

- src/main/webapp/WEB-INF/views/admin/oss/viewpopup.jsp
Project Identification or 3rd party > double click "ID" of oss > display popup with oss version list table and detail information
Increase the height of oss version list table.
AS-IS : 
TO-BE :
> Increase the height of oss version list table in  oss version list popup

- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
AS-IS
If user clicks Export button, user can download only FOSSLight Report
TO-BE
If user clicks Export button, then user can select file to download.  
Spdx files are the same as Spdx files from Notice Tab
> Self-check >  Add SPDX as well as FOSSLight Report to the export button download

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/service/OssService.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/java/oss/fosslight/util/ExcelUtil.java
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
- Fix the bug where OSS information is blank in mail when saving OSS.
-  Change the condition to check empty row when uploading OSS Report
- AS-IS: If OSS Name, OSS version, License, binary name and file path are blank.
- TO-BE : If OSS Name, OSS version, License, binary name, file path, Download location, Homepage and Copyright is blank.
- Fix a bug where only 1 Vulnerability list is shown when there is no version in OSS detail page.
- Project - Identification > 3rd Party Tab > Change nickname to OSS NAME when clicking Save.
> Fix a bug where only 1 Vulnerability list is shown when there is no version in OSS detail page

- src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
1) Rollback getVerificationSPDX_SpreadSheetExcelPost code
2) Export button depends on identification status
- project identification status is CONF (confirm)
If user clicks export button, then user can select a file to download
- project identification status is not CONF
If user clicks export button, then user immediately can download FOSSLight Report
> Export button depends on project identification status

- src/main/java/oss/fosslight/common/CommonFunction.java
Fix the bug that the row in which only Homepage or Copyright is entered is not loaded when uploading a report.
> Fix the bug that the row in which only Homepage or Copyright is entered is not loaded when uploading a report.

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/repository/OssMapper.java
- src/main/java/oss/fosslight/service/OssService.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
- src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
- Reduce the loading speed when entering the Identification tab by changing the Deactivate OSS check method.
- Remove the limit on the number of rows for the bulk edit button. 
- Change Bulk edit to GET -> POST so that many rows can be edited at once.
> Remove the limit on the number of rows for the bulk edit button

- Dockerfile
Pull request #675, #699 
Issue #601 
```diff
- COPY ./docs /app/docs
+ COPY ./LICENSES /app/LICENSES
```
Remove unused folder and add **license text files** to Docker image.
- [Dockerfile reference](https://docs.docker.com/engine/reference/builder/)
> Add license text files to docker image

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/util/ExcelUtil.java
- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
- This PR adds detail failure message to OSS bulk items.
- Required missing
- Duplicated (nickname or OSS name)
- Unconfirmed license
- Duplicated Version
- This PR moves status attribute to first
It shows only status fail or success, not includes fail reasons.
It shows not only status fail or success, but also fail reasons.
> Show detail failure messages in OSS bulk feature.

- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- src/main/webapp/WEB-INF/views/admin/oss/list-js.jsp
- src/main/webapp/WEB-INF/views/admin/system/sentMail-js.jsp
- src/main/webapp/WEB-INF/views/template/layout/admin/header.jsp
- Fix the bug that matches even if the Download location is not the same when clicking Check OSS Name.
- Change the link in the OSS registration and modification mail.
- Add the OSS rename record to the history list.
- Fix the bug where OSS Notice is not issued when project copy (Packaging confirm).
-  Fix the bug that changes to N/A even if OSS Notice is checked as General when copying a Packaging: N/A project.
> Fix download location check function

- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
Signed-off-by: Dongwon Kim <freshtuna@kakao.com>
This PR fix problem that copyright is not applied when copyright is edited in OSS Bulk.
Changing column name **ossCopyright** to **copyright** can fix problem
> Fix edited copyright not applied in OSS Bulk

- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
**This PR add triming logic to listable attributes in frontend.**
As a result,  elements of listable attributes are trimmed before bulk request.
**listable attributes** 
- ossNicknames
- declaredLicenses
- detectedLicenses
> Add triming logic to list attributes in OSS Bulk

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/service/OssService.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
Change background color of oss that failed to save in bulk registration.
1. Add `failOss` variable in `ossBulkReg-js.jsp` to save failed data as list.
2. Modified response body of "/oss/bulkRegAjax" API.
* Previous response body
```json
{
"res":true,
"value":[
{
"gridId": "1", 
"status": "O"
},
{
"gridId": "2", 
"status": "X (error message)", 
}
]
}
```
* After response body
```json
{
"res":true,
"value":[
{
"gridId": "1", 
"status": true,
"msg": "O"
},
{
"gridId": "2", 
"status": false,
"msg": "X (error message)"
}
]
}
```
https://user-images.githubusercontent.com/68562176/194705385-5f4b1289-773c-4e95-948a-2488acde8af6.mov
(Add `failOss` variable to save failed data as list)
1. Import excel.
2. Initalize `failOss`.
4. Save oss data in bulk.
5. Save failed data in `failOss` while checking …
> Highlight Oss data failed to save in red

- .github/workflows/release-publish.yml
- Dockerfile
Pull request: #675 
Issue: #722
I added [docker/setup-qemu-action](https://github.com/docker/setup-qemu-action) in workflow to build multi-arch images. And I reverted jdk base image to apply multi-arch build.
- linux/amd64
- linux/arm64/v8
- linux/arm/v7
- linux/ppc64le
- linux/s390x
- linux/amd64
A multi-arch image is a type of container image that may combine variants for different architectures, and sometimes for different operating systems. When running an image with multi-architecture support, container clients will automatically select an image variant that matches your OS and architecture.
- [Multi-arch build and images, the simple way](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/)
- [Multi-arch docker images …
> Use setup-qemu-action to build multi-arch images

- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
Fix a bug where the Homepage/Download Location is saved with a warning message included.
- If the Homepage/Download Location address is entered and saved differently from the registration, a warning message is displayed. If you save it again after that, a warning message is added to the existing address and saved.
Fix the error that occurs when the default internal url contains " in the license name.
> Fix a bug where the Homepage/Download Location is saved with a warning message included.

- .github/workflows/stale.yml
I added `stale.yml` to automatically close stalled issues and pull requests.
- Add a label "keep" on issues and pull requests can be exempt from automatically mark as "stale".
- If an update/comment occur on stale issues or pull requests, the stale label will be removed and the timer will restart.
- [actions/stale](https://github.com/actions/stale)
- [Closing inactive issues - GitHub Docs](https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues)
> Automatically close stalled issues and pull requests

- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/oss/syncpopup.jsp
- Possible to select other version of oss even if the information is same in oss sync
- Check oss name
-  If there is timeout to check redirect location, "invaild downlaod location" is displayed.
> Possible to select other version of oss even if the information is same in oss sync

- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/controller/VerificationController.java
- src/main/java/oss/fosslight/service/impl/LicenseServiceImpl.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
- src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
- src/main/resources/messages/validation.properties
- src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
- src/main/webapp/WEB-INF/views/admin/project/3rd-js.jsp
- Do not display the deactivated oss information in the result of auto analysis.
- Add logic to avoid null exception when checking obligation of license.
- Project > Identification, 3rd-party, self-check
- Display "Required oss name" warning message under the specific condition as below.
- oss name : "-"
- license : source obligation is included
- Adjust priority of warning message.
-  "Unconfirmed license" < "Specify OSS Name or put 1 license in a row"
- Project > Identification 
- When click "merge and save" button, display the information in bom tab under the specific condition as below.
- oss name : "-" 
- license : multi/dual license
- Improve the speed of saving self-check project.
- Remove the duplicated list in the result of auto analysis.
> Display "Required oss name" warning message when oss name is "-" and license has source obligation.

- .github/dependabot.yml
Signed-off-by: jongwooo <jongwooo.han@gmail.com>
This PR configures Dependabot for GitHub Actions.
Dependabot checks for new versions of your actions. Dependabot will raise pull requests for version updates for any outdated actions that it finds. After the initial version updates, Dependabot will continue to check for outdated versions of actions once a week.
Ref. https://github.com/spring-projects/spring-boot/pull/31567
> chore: Configure Dependabot for GitHub Actions

- CHANGELOG.md
- build.gradle
- src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
- src/main/java/oss/fosslight/service/ApiProjectService.java
- src/main/java/oss/fosslight/service/impl/ApiProjectServiceImpl.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- Fix the error that occurs when bom compares the same Project ID.
- Fix bug loading nickname incorrectly in oss save tab.
> Fix the error that occurs when bom compares the same Project ID

- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/resources/template/email/ossModify.html
- src/main/webapp/WEB-INF/views/admin/oss/ossAnalysisResultDetailpopup.jsp
- Fix a bug where a space is added at the beginning when there are more than two detected licenses when loading OSS.
- Fix templdate and data when mailing change.
> Fix a bug where a space is added at the beginning when there are more than two detected licenses when loading OSS

- src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/controller/PartnerController.java
- src/main/java/oss/fosslight/domain/CoCode.java
- src/main/java/oss/fosslight/domain/ComBean.java
- src/main/java/oss/fosslight/service/NvdDataService.java
- src/main/java/oss/fosslight/service/impl/ApiBatServiceImpl.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
- src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
- src/main/java/oss/fosslight/util/ExcelUtil.java
- src/main/java/oss/fosslight/util/StringUtil.java
- src/main/java/oss/fosslight/validation/T2BasicValidator.java
- src/main/java/oss/fosslight/validation/T2CoValidationResult.java
- src/main/java/oss/fosslight/validation/custom/T2CoOssValidator.java
Signed-off-by: jongwooo <jongwooo.han@gmail.com>
#777 
It is generally considered a best practice to use curly braces with if statements, even when the body of the if statement consists of only a single statement. This helps to avoid mistakes and makes the code easier to read and understand.
I found if statements without curly braces in the project through the following command:
```bash
$ find . -name '*.java' | xargs egrep '^\s*if[^\{]*\s*$' --no-filename
```
There are 311 if statements without curly braces, as calculated by the `wc -l` command, and 106 of them were actually corrected.
- [새로 입사한 개발자가 프로젝트에 기여하는 방법 한 가지 - 컬리 기술 블로그](https://helloworld.kurly.com/blog/fix-style-with-command/)
> Fix if statements without curly braces

- src/main/java/oss/fosslight/domain/Project.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
BIN(Android)
1. Upload the compressed notice file
2. Click "Save"
3. Click "x" to remove the compressed notice file
4. Click "Save"
5. Close project identify tab
6. Load project identify tab again
Before : 
Fail to remove auto generated notice.html file
After : 
Success to remove all files
> Bug fix - Fail to remove the compressed notice file in BIN(Android)

- src/main/java/oss/fosslight/controller/VulnerabilityController.java
Fix the bug that the Vulnerability popup is not searched if there is a space in the OSS Name.
> Fix the bug that the Vulnerability popup is not searched if there is a space in the OSS Name

- src/main/resources/template/notice/notice.txt
There was a typo in text format of the notice template.
> Fix a typo in the notice template

- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
Bug fix
- Even if the oss matched with name and version is existed and the entered download location is different from database, generate oss name by using "check oss name" based on the entered download location.
> Check oss name - the oss matched with name and version is existed and download location has "Not the same as property" warning message

- src/main/java/oss/fosslight/common/Url.java
- src/main/java/oss/fosslight/controller/UserController.java
src/main/oss/fosslight /common/Url.java
rename URL from AUTOCOMPLETE_CRAETOR_AJAX to AUTOCOMPLETE_CREATOR_AJAX,
AS-IS
`public static final String AUTOCOMPLETE_CRAETOR_AJAX = PATH + "/autoCompleteCreatorAjax";`
TO-BE
`public static final String AUTOCOMPLETE_CREATOR_AJAX = PATH + "/autoCompleteCreatorAjax";`
> Fix typo at Url

- src/main/java/oss/fosslight/util/StringUtil.java
String.concat() to StringBuilder append() in StringUtil.java
Hi, I've found a single usage of `String.concat()` in `StringUtil.java`, which is widely known to be bad in performance in Java's string concatenation. So I've changed it to StringBuilder based like the other utility methods.
> Change string concatenation method

- src/main/java/oss/fosslight/service/AutoIdService.java
parameter binaryName unused in Function.
Personally, looking at the semantics of the function, the binaryName parameter doesn't seem necessary.
AS-IS
```
private BinaryData findCloseBatOssWithTlshDistance(String binaryName, String tlsh, List<BinaryData> dbDataList)
```
TO-BE
```
private BinaryData findCloseBatOssWithTlshDistance(String tlsh, List<BinaryData> dbDataList);
```
> Remove Unused Parameter 'binaryName' in Function

- src/main/java/oss/fosslight/domain/CoMail.java
src/java/main/oss/fosslight/domain/CoMail.java
Fix a typo of CoMail's getSndSeq comment
**AS-IS**
```java
/**
*  //.
*
* @return the snd seq
*/
public String getSndSeq() {
return sndSeq;
}
```
**TO-BE**
```java
/**
* Gets the snd seq.
*
* @return the snd seq
*/
public String getSndSeq() {
return sndSeq;
}
```
> Fix a typo of CoMail's getSndSeq comment

- .github/workflows/release-publish.yml
I found deprecated code in /github/workflows/release-publish.yml.
We've been informed that we're not using Slack this year. We decided it would be more efficient for the program to remove unused features.
AS-IS:
Slack Workflow Notification feature still exists in program code even though it's disabled
TO-BE:
Remove unused Slack Workflow Notification features
> Remove unused Slack notification step

- db/initdb.d/fosslight_create.sql
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
closed #964
- AS-IS
Download Location in 'stackoverflow' does not apply to 'check os name' function
- TO-BE
Download Location in 'stackoverflow' apply to 'check os name' function
example)
[https://stackoverflow.com/revisions/{ID}/](https://stackoverflow.com/revisions/29867106/2) → stackoverflow-{ID}
https://stackoverflow.com/revisions/29867106/2 → stackoverflow-29867106
> OSS name has been changed.
> Add stackoverflow pattern for check oss name

- Dockerfile
Currently, our project uses double-ampersand(`&&`) for `RUN` scripts that run multiple commands in the Dockerfile.
Also, the `RUN` script in the Dockerfile is currently writing the double ampersand first, followed by the command.
I want to modify this so that the command is written first and the double-ampersand is written at the end of the line. 
I think this will make the script more readable, and it will also make it the same format as other fosslight projects' Dockerfiles.
**AS-IS**
```dockerfile
RUN chmod +x /app/wait-for /app/verify/verify  \
&& apt-get update  \
&& apt-get install -y --no-install-recommends netcat  \
&& rm -rf /var/lib/apt/lists/*  \
&& ln -s /bin/sh bash
```
**TO-BE**
```dockerfile
RUN chmod +x /app/wait-for /app/verify/verify && \
apt-get update && \
apt-get …
```
> Fix the RUN script format of Dockerfile

- src/main/java/oss/fosslight/controller/VerificationController.java
- src/main/java/oss/fosslight/service/VerificationService.java
- src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
closes #907 
- #907
Separate comments are left for each attached file. 
1. The comments generated for each attached file were combined
2. added to the comment's content generated when confrim.
> Combine comment into one when packaging confirm

- src/main/resources/oss/fosslight/repository/OssMapper.xml
This PR add watcher feature to https://github.com/fosslight/fosslight/issues/992
https://github.com/fosslight/fosslight/assets/81344634/5d02e9df-b25d-4de4-9e50-a1ea4383babb
https://github.com/fosslight/fosslight/assets/81344634/0e4e7884-17f2-40e2-874b-11178e6d6c2e
from getOssMasterList in OssServiceImpl, we should check ⬇
After importing data that meets the search conditions, data that has the same Ossname as the data **must be grouped and imported again into the new List.** 
So I fixed that code in OssMapper.
Example data was used to compare before and after. You can check it in the video !
> Fix bugs related to Vulnerability when searching OSS List

- .github/workflows/deploy-demo.yml
- .github/workflows/release-publish.yml
Resolve #948 
Related Issue: fosslight/.github#1
Currently, the `release-publish.yml` file is performing all the logic for the published event, resulting in a long action time. Also, there is a high dependency between jobs in the `release-publish.yml` file, which is not good for maintainability.
Therefore, by separating the jobs in the `release-publish.yml` file into different yml files, we want to reduce the dependency between each job and change the workflow from a publish event-centric workflow to a purpose-centric workflow for each job.
***
List of jobs performed by the `release-publish.yml` file
> 1. Update changelog
> 2. Build
> 3. Deploy demo
> 4. Deploy image
List of jobs performed by the `release-publish.yml` file
> 1. Update changelog
> 2. Deploy image
List of jobs performed by …
> Seperate Build and Deploy-demo from publish workflow

- src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/distribution-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
- src/main/webapp/WEB-INF/views/admin/project/secCommon-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/verification-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/verification-js.jsp
**1. Disable 'CheckOSSName' button in dep tab for user
Only admin use the button in dep tab**
It will look like this:
- for normal user:
- for admin:
**2. BOM tab should be shown first in Identification. therefore, fixed the tab number used when moving to identification**
> Bug fix in Identification (CheckOSSName Button in DEP tab, first tab)

- Dockerfile
Closes #825 
> NOTE: Adopt OpenJDK got moved to Eclipse Temurin and won't be updated anymore. It is highly recommended to migrate workflows from adopt to temurin to keep receiving software and security updates. See more details in the [Good-bye AdoptOpenJDK post](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/).
Replaced docker base image from [adoptopenjdk/openjdk11:jre-11.0.15_10-ubuntu](https://hub.docker.com/layers/adoptopenjdk/openjdk11/jre-11.0.15_10-ubuntu/images/sha256-47731bdd8db0cc80536915e5337d66008bf94f3e7ada123b6f3e09b7edcc739f?context=explore) to [eclipse-temurin/11.0.21_9-jre-jammy](https://hub.docker.com/layers/library/eclipse-temurin/11.0.21_9-jre-jammy/images/sha256-a4fa5b3c626e96ae0ca406dad4f2c41c492b9caeb05e72af9c58d767fe41af1b?context=explore …
> Replace docker base image from adopt to temulin

- src/main/resources/static/css/commonIframe.css
- src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
For UI consistency, the Check OSS Name button, which had disappeared, was made visible again and disabled.
AS-IS:
for user, "Check OSS Name" button is not shown in dep tab.
for admin, "Change OSS Name" button is enabled.
TO-BE:
for user, "Check OSS Name" button was displayed but disabled
for admin, "Change OSS Name" button visible but disabled in Check OSS Name popup in dep tab.
> Change CheckOSSName Button in DEP tab

- src/main/java/oss/fosslight/util/PdfUtil.java
close #1005 
- #1005 
Korean is broken in PDF.
> Fix to prevent Korean language from being broken in PDF

- .gitignore
- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
Modify bulk edit button disabled for user, like Change OSS Name button in DEP tab
As-is:
To-be:
> Bug fix/project/dep bulk edit btn
