- .github/workflows/pull-request.yml
- docker-compose.yml
> Add action for PR

- README.md
Add Description of ID and Password for Demo site 
I think this change is better for new users
> Add Description of ID and Password for Demo site

- README.md
- docs/README_kor.md
Add a spring boot badge to README
> Add a spring boot badge to README

- .github/workflows/pull-request.yml
Run PR action for all branches.
> Run PR action for all branches

- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/resources/application.properties
Fix a bug related to load properties.
Run the command "docker-compose up --build".
-> Failed to run FOSSLight.war with below error message.
```
web_1  | WARN  21-07-31 11:40:24[main] [o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext:557] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'coMailManager' defined in URL [jar:file:/app/FOSSLight.war!/WEB-INF/classes!/oss/fosslight/domain/CoMailManager.class]: Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError
816
web_1  | INFO  21-07-31 11:40:24[main] [o.s.o.j.LocalContainerEntityManagerFactoryBean:597] - Closing JPA EntityManagerFactory for persistence unit 'default'
817 …
```
> Fix a bug related to load properties

- src/main/java/oss/fosslight/controller/DownloadProcController.java
Signed-off-by: kimtaehyun98 <kimtaehyun98@naver.com>
change value name "encordedFilename" to "encodedFilename"
> Typo in Class

- src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
* Add project search drop condition
* Add drop condition description to project search api in swagger-ui
```bash
curl -X GET "http://localhost:8180/api/v1/prj_search?status=DROP" -H "accept: application/json" -H "_token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZm9zc2xpZ2h0Lm9yZyJ9.3jWpmXwz73emxQ6tYjf1nkecLK3Br6Jth08trgF-gxQ"
```
```json
{
"data": {
"record": 1,
"content": [
{
"prjId": 1,
"prjName": "Test Project 1",
"prjVersion": "",
"updateDate": "2021-08-11",
"createDate": "2021-08-11",
"identificationStatus": "Progress",
"verificationStatus": "",
"distributionStatus": "",
"distributionType": "General Model",
"networkService": "YES",
"notice": "General",
"priority": "P2",
"status": "Drop",
"noticePlatform": ""
}
]
},
"success": true,
"code": "100",
"msg": ""
} …
```
> Add DROP status to project search

- src/main/webapp/WEB-INF/views/admin/project/edit.jsp
- Move the Drop button to the right of the Delete button in "Project > Basic Information"
- The input type(id="drop") has been moved from the "right" class to the "left" class. in project/edit.jsp
> Move the Drop button to the right of the Delete button in "Project > Basic Information"

- .github/workflows/release-publish.yml
* Using the matrix function of Github actions, both develop and main branches will be applied automatically.
* If you want to add a new branch Just add it to the matrix of github actions.
```
strategy:
matrix:
ref: [main, develop, other branches.....]
```
There is no changelog in main branch and develop branch yet.
Released branch feature/issue-57 for testing.
changelog is committed to each branch.
|main|develop|
|:--:|:--:|
|![스크린샷 2021-08-13 오후 3 20 31](https://user-images.githubusercontent.com/32615702/129313648-c10c819f-0207-4b02-934c-59e0bf63e190.png)|![스크린샷 2021-08-13 오후 3 21 29](https://user-images.githubusercontent.com/32615702/129313729-dc72824c-5a79-4db6-92dc-7bfb760a55cb.png)|
> Add auto-updating CHANGELOG.md on develop branch

- .github/workflows/release-publish.yml
Deploy the latest release to demo.fosslight.org
> Deploy the latest release to demo.fosslight.org

- src/main/webapp/WEB-INF/views/admin/license/view-js.jsp
Signed-off-by: ubermen5che <ubermen5ch1308@gmail.com>
PR about issue #59 
Fix `Uncaught TypeError` caused by type check error.
> Fix a bug for type check error.

- src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
Signed-off-by: kimtaehyun98 <kimtaehyun98@naver.com>
In the Project List > change status button, when the reviewer clicks the Reopen/Complete button, it can be OK even if nothing is written in the comment.
> Change Admin can Restart/Complete with no comment

- src/main/resources/template/email/vulnerabilityInfo.html
Signed-off-by: Youn-Sung Hwang <acafela91@gmail.com>
- Issue : #64 
- Add CVE detail link to _vulnerability discovered notification_ 
> Add CVE link to vulnerability discovered mail body (#64)

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/resources/static/css/commonIframe.css
- src/main/webapp/WEB-INF/views/admin/oss/view-js.jsp
-  issue: [Add ability to allow users to check Detected Licensing details. #44](https://github.com/fosslight/fosslight/issues/44)
-  Add a function to check details detected license
-  Add CSS for detected license text color
- The detected licenses added to OSS cairo during the test were arbitrarily added from the admin account.
**Code reviews are always welcome**
Thank you
> Add a function to check details detected license.

- .github/workflows/release-publish.yml
- CHANGELOG.md
Modify github action to deploy 30 seconds after release.
> Modify github action to deploy 30 seconds after release

- .github/release-drafter-config.yml
* Add label:improvement to also appear as child of Feature in release draft
> Add label:improvement to also appear as child of Feature in release draft

- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
Signed-off-by: hyewoncc <hyewoncc@gmail.com>
Fix typo 'SoruceCode' to 'SourceCode' in Self-Check
> Fix typo 'SourceCode' in Self-Check

- src/main/webapp/WEB-INF/views/admin/system/vulnerabilityHistory-js.jsp
Signed-off-by: kimtaehyun98 <kimtaehyun98@naver.com>
Fix header column names of Vulnerability Log table
-  "CVE ID" → "CVE ID (From)"
-  "CVSS Score" → "CVSS Score (From)" 
- "CVE ID To" → "CVE ID (To)"
- "CVSS Score To" → "CVSS Score (To)"
> Fix header column names of Vulnerability Log table

- src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
> Drop button requires comment

- src/main/webapp/WEB-INF/views/admin/license/list.jsp
- src/main/webapp/WEB-INF/views/admin/oss/list.jsp
- src/main/webapp/WEB-INF/views/admin/partner/list.jsp
- src/main/webapp/WEB-INF/views/admin/project/list.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/list.jsp
Signed-off-by: sw-develop <psw00719@naver.com>
Rename "Excel Download" Button to "Export" in License List, OSS List, Project List, 3rd Party List, Self-Check List
> Rename 'Excel Download' Button to 'Export'

- src/main/resources/static/css/commonIframe.css
- src/main/webapp/WEB-INF/views/admin/common/gridCommonFn.jsp
* Add license information display when clicking the Restriction icon
> Add license information display when clicking the Restriction icon

- src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
- Modify pop-up phrases that occur when you press the reopen button in Project > Basic Information
- Creator Date : -> Created Date
- delete this phrase "Are you sure you want to reject?"
> Modify pop-up phrases that occur when you press the reopen button

- .github/workflows/pull-request.yml
- .gitignore
- docker-compose.yml
- mail/config/postfix-accounts.cf
I added a mail server for fosslight.
The mail server is based on [docker-mailserver](https://hub.docker.com/r/mailserver/docker-mailserver).
```
Mailserver: fosslight_mail or mail
Email Address: anyting
Port: 25 or 587
Encoding: UTF-8
Username: no-reply@fosslight.org
Password: fosslight
```
if you used docker-compose environment, You should write **mail** or **fosslight_mail** on the Mail Server form. 
And web server restart after press the save button.
Configuration are reflected only when the server is restarted. I think it's a bug.
```
Mailserver: 127.0.0.1
EmailAddress: anything
Port: 25 or 587
Encoding: UTF-8
Username: no-reply@fosslight.org
Password: fosslight
```
if you used local environment, write **127.0.0.1** on the Mail Server form. 
Others are same.
If the smtp setting is …
> Add Docker mailserver in docker-compose

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/3rd-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/bin-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/binAndroid-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/bom-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/src-js.jsp
Added - 3rd party/project status check function
Changed - OSS Sync Function
> 3rd party/project status check function

- src/main/java/oss/fosslight/domain/CoMailManager.java
(Please describe what this PR do.)
This PR updates a part of the comments written in Korean
> Translate some korean comments to english

- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
Exclude from 'Check OSS Name' unless it is an 'Unconfirmed open source'
> Exclude from 'Check OSS Name' unless it is an 'Unconfirmed open source'

- src/main/java/oss/fosslight/controller/OssController.java
Signed-off-by: doggai10 <doggai77@gmail.com>
modify OSS controller that allow users to search download location regardless of https://, http://, www
first check HttpServletRequest parameter homepage and convert url.
if homepage url starts with http:// or www, OSS search couldn't find OSS that has exact same download location.
so if homepage starts with http:// or www., convert url that starts with https:// and save homepage url using setHomepage function.
-test results
> Search website regardless of http://, https://, www.

- .github/workflows/pr-close.yml
Add deploy action when develop is merged.
Deploying will restart the site, http://dev.fosslight.com.
> Add deploy action when develop is merged

- .github/workflows/pr-close.yml
Run docker with sudo privileges.
> Run docker with sudo privileges

- .github/workflows/pr-close.yml
Remove unnecessary sleep from git actions.
> Remove unnecessary sleep from git actions

- src/main/webapp/WEB-INF/views/admin/selfCheck/viewpopup.jsp
* add description column to jqgrid (hidden:true)
* add User Guide and Restriction to license popup
* if there are no restrictions, user guide, or license text, it will not be displayed. 
|before|after(all)|
|:--:|:--:|
|![image](https://user-images.githubusercontent.com/32615702/133382486-73660ceb-2d99-48b3-b8d7-1ca978d1b58e.png)|![스크린샷 2021-09-15 오후 4 47 57](https://user-images.githubusercontent.com/32615702/133392523-d6e591aa-5841-4cd9-9cb8-18e9695e85e1.png)|
|after(no restriction)|after(no user guide)|
|:--:|:--:|
|![스크린샷 2021-09-15 오후 4 47 31](https://user-images.githubusercontent.com/32615702/133392454-561108f8-a290-46f9-9344-baaa5bca4eb2.png)|![스크린샷 2021-09-15 오후 4 48 19](https://user-images.githubusercontent.com/32615702/133392581-3f351738-30ef-413a-be75-8045 …
> Add User Guide and Restriction to license popup

- src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
- src/main/java/oss/fosslight/api/controller/v1/ApiSelfCheckController.java
- src/main/java/oss/fosslight/service/ApiProjectService.java
- src/main/java/oss/fosslight/service/impl/ApiProjectServiceImpl.java
- src/main/java/oss/fosslight/util/ExcelUtil.java
* Add ```getSheetNames``` method to ```ExcelUtil``` to retrieve Sheets with specific words (Extracted for reuse in future BIN)
* Add a ```String[] sheet``` parameter containing the sheet information to be imported to the ```getSheetData``` method
* Change parameters of ```getSheetData``` method in ```oss_report_selfcheck```, ```oss_report_src```, ```oss_report_bin``` controller
> SRC, SRC_A, SRC_B sheet
> src/cairo, src/cimg
> src_a/cairo, src_a/cimg
> src_b/cairo, src_b/cimg
> only SRC sheet import and save
|swagger-ui|web|
|:--:|:--:|
|![스크린샷 2021-09-16 오후 7 52 32](https://user-images.githubusercontent.com/32615702/133599782-c1aa8237-bb6a-4e17-8eac-497e1be9d76f.png)|![스크린샷 2021-09-16 오후 7 53 13](https://user-images.githubusercontent.com/32615702/133599862-ba071f93-88ea-49 …
> Change load all sheets starting with SRC in oss_report_src (REST_API)

- Dockerfile
- build.gradle
- src/main/java/oss/fosslight/domain/ComBean.java
- src/test/java/oss/fosslight/controller/ProjectControllerIntegrationTest.java
Signed-off-by: jongun.chae <cha452jg@gmail.com>
Initialize test code setting with Junit 5. Also, I made test code for creating a project. 
Firstly, create a project. Then, read it using other API to check whether it correctly create or not.
> Initialize test code setting

- .github/workflows/release-publish.yml
- CHANGELOG.md
> Exclude test on release

- src/main/java/oss/fosslight/config/RestTemplateConfig.java
- src/main/resources/application.properties
* set RestTemplate timeout, connection pool
* add timeout and connection-pool settings to application.properties
> RestTemplate config for task 1

- src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
Information > Drop button, you can drop the project without writing any comments.
However, I think it will be helpful for future projects when the reason for the drop is clearly stated.
Therefore, when you click the drop button, if you have not entered a comment, a message appears asking you to enter a comment.
> Check whether comments are entered when the drop button is clicked

- src/main/resources/template/email/licenseInfo.html
- src/main/resources/template/email/licenseModify.html
- src/main/resources/template/email/ossInfo.html
- src/main/resources/template/email/ossModify.html
| Before |  After
| -- | -- 
| ![image](https://user-images.githubusercontent.com/17478634/135762671-cced59f7-9c02-4b1d-a40a-0226c3072a8c.png) | ![image](https://user-images.githubusercontent.com/17478634/135762698-e028128a-c931-4844-bb8c-2cd7c594d8a2.png)
> Fix nickname typo in mail template

- build.gradle
- src/main/java/oss/fosslight/controller/SPDXDownloadController.java
- src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
- src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
- src/main/java/oss/fosslight/util/SPDXUtil2.java
* before : Convert spdx files using spdx-tools jar in cmd
* after : 
1. Add the spdx tools java dependency and convert the file using the SpdxConverter method
* version used org.spdx:tools-java 1.0.2 (15-Jul-2021 release)
* mavencentral : https://search.maven.org/artifact/org.spdx/tools-java/1.0.2/jar
* github release : https://github.com/spdx/tools-java
2. Change null value in Package information sheet of SDPX (spreadsheet)
* Download location : NONE
* Copyright : NOASSERTION
> Delete spdx-tools jar file and add spdx tools java dependency

- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
Changed - Recover Missing Messages
> Changed - Recover Missing Messages

- src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
> https://www.kernel.org -> invalide download location (not tailling slash)
> Fix SPDX convert error (when invalid download location)

- build.gradle
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- Fix the bug where all rows are not updated in the Check OSS Name function.
- When sending a mail merging to another OSS while deleting OSS, nickname change is output.
> Update Check OSS Name Function

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
- src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
- src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
* Refactor Check License, Check OSS Name
> Refactor Check License, Check OSS Name

- src/main/java/oss/fosslight/common/CoPostConstruct.java
- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/config/AppConfig.java
- src/main/java/oss/fosslight/config/CustomAuthenticationProvider.java
- src/main/java/oss/fosslight/controller/ComplianceController.java
- src/main/java/oss/fosslight/controller/ImageViewController.java
- src/main/java/oss/fosslight/controller/LicenseController.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/controller/PartnerController.java
- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/java/oss/fosslight/controller/UserController.java
- src/main/java/oss/fosslight/controller/VerificationController.java
- src/main/java/oss/fosslight/domain/CoMail.java
- src/main/java/oss/fosslight/interceptor/AjaxInterceptor.java
- src/main/java/oss/fosslight/service/NvdDataService.java
- src/main/java/oss/fosslight/service/impl/LicenseServiceImpl.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
- src/main/java/oss/fosslight/service/impl/SystemConfigurationServiceImpl.java
- src/main/java/oss/fosslight/service/impl/VulnerabilityServiceImpl.java
- src/main/java/oss/fosslight/util/CompressUtil.java
- src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
- src/main/java/oss/fosslight/validation/T2CoValidator.java
Change e.printStackTrace(); to log.debug(e.getMessage());
> Fix the vulnerability for inapproate error message

- src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
- src/main/java/oss/fosslight/common/CoCodeManager.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/service/impl/ApiFileServiceImpl.java
- src/main/java/oss/fosslight/service/impl/ApiOssServiceImpl.java
- src/main/java/oss/fosslight/service/impl/FileServiceImpl.java
- src/main/java/oss/fosslight/service/impl/HistoryServiceImpl.java
- src/main/java/oss/fosslight/service/impl/MailServiceImpl.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/java/oss/fosslight/util/DateUtil.java
- src/main/java/oss/fosslight/util/FileUtil.java
Fix NPE
common/
controller/
service/
util/
> Fix Null pointer exception 

- src/main/java/oss/fosslight/domain/BinaryMaster.java
- src/main/java/oss/fosslight/domain/CoMail.java
- src/main/java/oss/fosslight/domain/CodeBean.java
- src/main/java/oss/fosslight/domain/ComBean.java
- src/main/java/oss/fosslight/domain/File.java
- src/main/java/oss/fosslight/domain/LicenseMaster.java
- src/main/java/oss/fosslight/domain/OssMaster.java
- src/main/java/oss/fosslight/domain/PartnerMaster.java
- src/main/java/oss/fosslight/domain/Project.java
- src/main/java/oss/fosslight/domain/ReportCombean.java
Change public method that return private type to public method that
return copy.
> Fix the vulnerability for public method that return private type

- src/main/java/oss/fosslight/domain/BinaryMaster.java
- src/main/java/oss/fosslight/domain/CodeBean.java
- src/main/java/oss/fosslight/domain/ComBean.java
- src/main/java/oss/fosslight/domain/File.java
- src/main/java/oss/fosslight/domain/LicenseMaster.java
- src/main/java/oss/fosslight/domain/OssMaster.java
- src/main/java/oss/fosslight/domain/PartnerMaster.java
- src/main/java/oss/fosslight/domain/Project.java
- src/main/java/oss/fosslight/domain/ReportCombean.java
Change behavior that public array is assigned to private variable into
behavior that copy is assigned to private variable.
> Fix the vulnerability that public array is assigned to private variable

- src/main/java/oss/fosslight/repository/OssMapper.java
- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
> Add Check License in Self-Check

- src/test/java/oss/fosslight/controller/OssControllerTest.java
- src/test/java/oss/fosslight/controller/PackingRequestTest.java
- src/test/java/oss/fosslight/controller/ProjectControllerIntegrationTest.java
- src/test/java/oss/fosslight/controller/ProjectIdentificationRequestReviewIntegrationTest.java
- src/test/java/oss/fosslight/controller/ProjectIdentificationReviewConfirmIntegrationTest.java
- src/test/java/oss/fosslight/controller/SelfCheckControllerIntegrationTest.java
Create integration test codes.
> Create integration test codes

- CHANGELOG.md
- src/main/resources/messages/validation.properties
- Modify the length of the license name and revert it.
> Modify the length of the license name and revert it

- src/main/java/oss/fosslight/common/Url.java
- src/main/java/oss/fosslight/controller/LicenseController.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/service/LicenseService.java
- src/main/java/oss/fosslight/service/impl/LicenseServiceImpl.java
When double-clicking the license name in the OSS Table, the License Details tab is displayed.
> Update OSS Table Function

- src/main/java/oss/fosslight/service/NvdDataService.java
- Fixe heap memory issue when registering CPE Match Feed.
> Fix heap memory issue when registering CPE Match Feed

- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
* fix check oss name save error
> Fix check oss name save error

- src/main/java/oss/fosslight/common/CoConstDef.java
- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/common/DependencyType.java
- src/main/java/oss/fosslight/common/ExternalLicenseServiceType.java
- src/main/java/oss/fosslight/common/ExternalServiceType.java
- src/main/java/oss/fosslight/service/AutoFillOssInfoService.java
- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
* license inquiry function using github API (not oss version and download location)
* **github token is required for testing**
> Add license inquiry function using external API (Github, Clearly Defined)

- db/initdb.d/fosslight_create.sql
- src/main/java/oss/fosslight/common/CoConstDef.java
- src/main/java/oss/fosslight/common/Url.java
- src/main/java/oss/fosslight/config/SecurityConfig.java
- src/main/java/oss/fosslight/controller/ConfigurationController.java
- src/main/java/oss/fosslight/domain/Configuration.java
- src/main/java/oss/fosslight/domain/T2Users.java
- src/main/java/oss/fosslight/repository/ConfigurationMapper.java
- src/main/java/oss/fosslight/service/ConfigurationService.java
- src/main/java/oss/fosslight/service/impl/ConfigurationServiceImpl.java
- src/main/resources/messages/message.properties
- src/main/resources/oss/fosslight/repository/ConfigurationMapper.xml
- src/main/resources/oss/fosslight/repository/T2UserMapper.xml
- src/main/webapp/WEB-INF/views/admin/configuration/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/configuration/edit.jsp
- src/main/webapp/WEB-INF/views/session/login.jsp
- src/main/webapp/WEB-INF/views/template/layout/admin/header.jsp
Save language settings per user.
- Default value : en_US
> Save language settings per user

- src/main/java/oss/fosslight/domain/LicenseMaster.java
- src/main/java/oss/fosslight/domain/OssMaster.java
> Fix a vulnerability for public methods that return private array

- src/main/java/oss/fosslight/domain/LicenseMaster.java
- src/main/java/oss/fosslight/domain/OssMaster.java
Fix the vulnerability that returns private variable and array.
> Fix the vulnerability that returns private variable and array

- src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/controller/PartnerController.java
- src/main/java/oss/fosslight/domain/CoCode.java
- src/main/java/oss/fosslight/service/impl/ApiFileServiceImpl.java
- src/main/java/oss/fosslight/service/impl/FileServiceImpl.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
- src/main/java/oss/fosslight/validation/T2CoValidator.java
Eliminate Null Point Exception
> Eliminate Null Point Exception

- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/java/oss/fosslight/domain/ImageView.java
- src/main/java/oss/fosslight/util/CompressUtil.java
- src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
- src/main/java/oss/fosslight/util/ExcelUtil.java
- src/main/java/oss/fosslight/util/FileUtil.java
Put the method "close()" into appropriate position.
> Fix a vulnerability for resource leak

- build.gradle
- src/main/java/oss/fosslight/common/XssFilter.java
- src/main/java/oss/fosslight/controller/LicenseController.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/resources/messages/validation.properties
- I add lucy xss filter in license, oss, project controller for list_ajax and autocomplete_ajax.
- <> characters are not allowed to be entered for the following items.
- License name, License nickname, License Short ID, OSS Name, OSS nickname, OSS Version, Project name.
> Fix a cross-site scripting issue

- src/main/java/oss/fosslight/domain/CoMailManager.java
> Fix a bug for CoMailManager.java

- CHANGELOG.md
- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- Fix the license duplication bug in Check License.
> Fix the license duplication bug in Check License

- src/main/java/oss/fosslight/repository/CodeMapper.java
- src/main/java/oss/fosslight/service/impl/CodeServiceImpl.java
- src/main/java/oss/fosslight/service/impl/SystemConfigurationServiceImpl.java
- src/main/resources/oss/fosslight/repository/CodeMapper.xml
- src/main/webapp/WEB-INF/views/admin/system/configuration.jsp
* change token to invisible
* change not to save if token is empty string
> Change token to invisible

- src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
Fix OSS Notices to include SPDX (json) and SPDX (yaml)
1. Packaging - Notice Tab > Click SPDX (SpreadSheet), Click SPDX (TAG), Click SPDX (json), SPDX (yaml) > Confirm.
2. Unzip downloaded file.
Resolves #215
> Fix OSS Notices to include SPDX (json) and SPDX (yaml)

- CONTRIBUTING.md
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/project/verification-js.jsp
- Fix the bug where the notice file format is unchecked whenever the status is changed.
- Fix OSS Notices to include SPDX (json) and SPDX (yaml).
- Update contribution guide. (Remove label setting)
> Fix the bug where the notice file format is unchecked whenever the status is changed

- .github/workflows/pull-request.yml
- src/main/java/oss/fosslight/controller/ProjectController.java
- src/test/java/oss/fosslight/controller/ProjectControllerIntegrationTest.java
- Add test to github action for PR.
> Add test to github action for PR

- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
* Add Check License to Project tab (bin, android)
> Add Check License to Project tab (bin, android)

- CHANGELOG.md
- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
- Add a Check License button to your Project.
- If you change the license by clicking the Check License button in the project, leave a change history as a comment.
> Add a Check License button to your Project

- src/main/resources/static/js/ckeditor/config.js
adjust textarea height according to content height.
Test 1. Project Identification page
Test 2. ckeditor function test
Test 3. Image copy and paste test
Test 4. Project Identification > packaging reject button
Test 5. paste from word
same as old version
> Apply autogrow to ckeditor

- src/main/java/oss/fosslight/service/NvdDataService.java
- src/main/resources/static/js/ckeditor/config.js
- Fix heap memory issue when registering CPE Data Feed (GC Limit).
> Fix heap memory issue when registering CPE Data Feed (GC Limit)

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/service/AutoFillOssInfoService.java
- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
- src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
Github API error message
* Github Token Invalid : Token has expired or is not registered.
* API usage limit : API usage limit has been exceeded.
* API connect fail : API service connect failed.
Clearly Defined error message
* API usage limit : API usage limit has been exceeded.
* API connect fail : API service connect failed.
> Add External Service health check

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/service/AutoFillOssInfoService.java
- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
- src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
Signed-off-by: riyenas0925 <riyenas0925@gmail.com>
- In Check License, print the message that external service connection is not possible.
> Check License > print the message that external service connection is not possible

- src/main/resources/static/js/ckeditor/config.js
> Change max height of editor

- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
Update message.
Change redirect url.
1. English
2. Korean
3. redirect
> Add multilingual support about delivery form

- src/main/java/oss/fosslight/domain/CoMailManager.java
> Eliminate null pointer exception in CoMailManager

- src/main/java/oss/fosslight/common/Url.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
- Add a function to change the OSS table in bulk (incomplete).
> Add a function to change the OSS table in bulk (incomplete)

- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
Signed-off-by: riyenas0925 <riyenas0925@gmail.com>
- Do not print () if the OSS version is null when leaving a comment in the Check License
> Do not print () if the OSS version is null when leaving a comment in the Check License

- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
- src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
- src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
|  |kor|eng|
|:--:|:--:|:--:|
|check license| ![image](https://user-images.githubusercontent.com/32615702/146321229-44a245b8-e945-4a6b-9a43-9c95041ddba3.png) | ![image](https://user-images.githubusercontent.com/32615702/146320970-02b6f955-e9ae-4fc0-bc4e-95eae2c22d05.png) |
|check oss name| ![image](https://user-images.githubusercontent.com/32615702/146321131-26de596b-c3d8-4018-80b6-102c2044fa70.png) | ![image](https://user-images.githubusercontent.com/32615702/146321046-b625398d-3a56-4dfd-b38d-1d3073511747.png) |
> Support Check OSS Name, Check License multilingual

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
- src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
- src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
- Eliminate null pointer exception.
- Support Check OSS Name, Check License multilingual.
> Eliminate null pointer exception

- src/main/java/oss/fosslight/common/CoConstDef.java
* Fixe an error that could not be retrieved if the download location contains a version.
[FOSSLight-Report-6-test6_20211220.xlsx](https://github.com/fosslight/fosslight/files/7743298/FOSSLight-Report-6-test6_20211220.xlsx)
> Fix mismatching error in Check License

- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
- src/main/webapp/WEB-INF/views/admin/project/distribution-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/distribution.jsp
- src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/edit.jsp
- src/main/webapp/WEB-INF/views/admin/project/verification-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/verification.jsp
* Send comments to Creator, Watcher, and Reviewer by mail. (Get rid of pop-ups to choose who to send to.)
* 3rd party, project(android, src, bin, bom), packaging(packaging, notice) tab
> Send comments to Creator, Watcher, and Reviewer by mail.

- src/main/java/oss/fosslight/common/CoConstDef.java
- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
- src/main/webapp/WEB-INF/views/admin/project/distribution-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/distribution.jsp
- src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/edit.jsp
- src/main/webapp/WEB-INF/views/admin/project/verification-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/verification.jsp
- Remove the recipient selection window when sending comments by e-mail.
- Check OSS Name > Change download location to `git:// `from `https://`
- Update distritbution related function.
> Check OSS Name > Change download location to git:// from https://

- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/domain/ComBean.java
- src/main/java/oss/fosslight/domain/CommentsHistory.java
- src/main/resources/oss/fosslight/repository/BinaryDataHistoryMapper.xml
- src/main/resources/oss/fosslight/repository/CodeMapper.xml
- src/main/resources/oss/fosslight/repository/CommentMapper.xml
- src/main/resources/oss/fosslight/repository/DashboardMapper.xml
- src/main/resources/oss/fosslight/repository/HistoryMapper.xml
- src/main/resources/oss/fosslight/repository/NoticeMapper.xml
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
- src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
- src/main/resources/oss/fosslight/repository/SentMailMapper.xml
- src/main/resources/oss/fosslight/repository/StatisticsMapper.xml
- src/main/resources/oss/fosslight/repository/T2UserMapper.xml
- src/main/resources/oss/fosslight/repository/VulnerabilityHistoryMapper.xml
- src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
I attached tests results file.
Delete ${sidx}, ${sord}, ${schKeywordSql}
[tests.docx](https://github.com/fosslight/fosslight/files/7725960/tests.docx)
Delete ${filterCondition}
[VulnerabilityHistoryMapper.docx](https://github.com/fosslight/fosslight/files/7748637/VulnerabilityHistoryMapper.docx)
For test, you can follow below instruction.
Delete ${sidx}, ${sord} test
Delete ${schKeywordSql} test
Delete ${filterCondition} test
Type word to search
It's new version of "Fix the vulnerability for SQL Injection #261" and "Delete ${filterCondition} for defending sqlInjection #294"
> Delete ${sidx}, ${sord}, ${schKeywordSql} and ${filterCondition} for defending SQL Injection 

- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/java/oss/fosslight/domain/ComBean.java
- src/main/java/oss/fosslight/domain/CommentsHistory.java
- src/main/resources/oss/fosslight/repository/BinaryDataHistoryMapper.xml
- src/main/resources/oss/fosslight/repository/CodeMapper.xml
- src/main/resources/oss/fosslight/repository/CommentMapper.xml
- src/main/resources/oss/fosslight/repository/DashboardMapper.xml
- src/main/resources/oss/fosslight/repository/HistoryMapper.xml
- src/main/resources/oss/fosslight/repository/NoticeMapper.xml
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
- src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
- src/main/resources/oss/fosslight/repository/SentMailMapper.xml
- src/main/resources/oss/fosslight/repository/StatisticsMapper.xml
- src/main/resources/oss/fosslight/repository/T2UserMapper.xml
- src/main/resources/oss/fosslight/repository/VulnerabilityHistoryMapper.xml
- src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
Update distribution mailing condition.
> Update distribution mailing condition.

- src/main/java/oss/fosslight/common/CustomXssFilter.java
- src/main/java/oss/fosslight/controller/LicenseController.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/controller/ProjectController.java
- Fix the bug where `&amp;` is added to the License List.
> Fix xss filter for License List with &amp;

- CHANGELOG.md
- src/main/java/oss/fosslight/common/CustomXssFilter.java
- src/main/java/oss/fosslight/controller/LicenseController.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/webapp/WEB-INF/tiles.xml
- src/main/webapp/WEB-INF/views/admin/common/gridCommonFn.jsp
- src/main/webapp/WEB-INF/views/admin/oss/ossBulkEditPopup.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
- src/main/webapp/WEB-INF/views/admin/project/bin-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/binAndroid-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
- src/main/webapp/WEB-INF/views/admin/project/src-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
- src/main/webapp/WEB-INF/views/template/layout/admin/scripts_popup4.7.jsp
- Add the Bulk Edit funtion.
- Edit the url for git:// or .git in Check OSS Name.
> Add the Bulk Edit funtion

- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
* Fixed an issue where an error occurred when there was no searched license
> Fix infinite loading bug when clicking Check License

- src/main/resources/oss/fosslight/repository/BinaryDataHistoryMapper.xml
- src/main/resources/oss/fosslight/repository/CodeMapper.xml
- src/main/resources/oss/fosslight/repository/DashboardMapper.xml
- src/main/resources/oss/fosslight/repository/HistoryMapper.xml
- src/main/resources/oss/fosslight/repository/NoticeMapper.xml
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
- src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
- src/main/resources/oss/fosslight/repository/SentMailMapper.xml
- src/main/resources/oss/fosslight/repository/StatisticsMapper.xml
- src/main/resources/oss/fosslight/repository/T2UserMapper.xml
- src/main/resources/oss/fosslight/repository/VulnerabilityHistoryMapper.xml
- src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
- Fix Vulnerability, Sent mail list not searchable bug.
> Fix Vulnerability, Sent mail list not searchable bug

- src/main/java/oss/fosslight/common/CoConstDef.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/repository/OssMapper.java
- src/main/java/oss/fosslight/service/PartnerService.java
- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
- src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
* Support Check OSS Name and Check License in 3rd party tab
* Add the Check License, Check OSS Name results as comments
> Add Check OSS Name and Check License function in 3rd party

- src/main/java/oss/fosslight/common/CoConstDef.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/repository/OssMapper.java
- src/main/java/oss/fosslight/service/PartnerService.java
- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
- src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
- src/main/java/oss/fosslight/util/ExcelUtil.java
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
- src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
- src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
Packaging > Notice tab
- Fix the bug that occurs when checking hide version in OSS notice.
> Fix the bug that occurs when checking hide version in OSS notice

- src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
* Add Check License function in Self-Check page
> Add Check License function in Self-Check page

- src/main/java/oss/fosslight/util/ExcelUtil.java
* Fix License and Comment output when loading SPDX
> Fix License and Comment output when loading SPDX

- src/main/java/oss/fosslight/util/ExcelUtil.java
* Delete License output when loading SPDX
> Delete License output when loading SPDX

- src/main/java/oss/fosslight/util/ExcelUtil.java
* When uploading SPDX, add License to Comment only if OR or AND is included in License.
> Add display in comments only when License is OR, AND

- src/main/java/oss/fosslight/util/ExcelUtil.java
Signed-off-by: riyenas0925 <riyenas0925@gmail.com>
- Load comment when loading SPDX.
> Load comment when loading SPDX

- build.gradle
> Update version to 1.2.24

- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/bin-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/binAndroid-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/src-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
- Remove license duplication in one cell.
- Change the column order in 3rd Party's OSS Table.
> Remove license duplication in a cell

- CHANGELOG.md
- build.gradle
> Update version to 1.2.25

- src/main/java/oss/fosslight/CoTopComponent.java
- src/main/java/oss/fosslight/api/controller/v1/ApiPartnerController.java
- src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
- src/main/java/oss/fosslight/api/controller/v1/ApiSelfCheckController.java
- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/controller/LicenseController.java
- API > Fix the bug that the admin account does not have permission to the project.
- Auto ID > Fix the bug where the license is not automatically selected according to the license type priority for OSS with OR.
- Mailing (License) > Fix the bug where the email arrives as if it was fixed even if the license website was not modified.
> Fix bugs related to Auto ID, mailing, and check license.

- build.gradle
> Update version to 1.2.26

- CHANGELOG.md
- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
- src/main/resources/static/css/common.css
- src/main/resources/template/notice/notice.html
- src/main/webapp/WEB-INF/views/admin/system/processGuide-js.jsp
- Project List > BOM Compare > Fix the bug where the OSS Name does not match if there is a space.
- Help & Guide > Fix the bug that cannot be submitted after editing the content.
- Mailing - License > Fix the bug where the email is sent even if the website is not modified.
- Project > OSS Table > Fix the bug in which a Declared warning message is displayed for a License whose license short Identifier is null.
- Delete the arrow from the left menu.
> Delete the arrow from the left menu

- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
Reorder user comments before email default content.
> Change user comments to the front

- build.gradle
> Update version to 1.2.28

- build.gradle
- src/main/resources/template/email/ossInfo.html
- src/main/resources/template/email/ossModify.html
- Change the format of OSS mail.
- Remove / from your OSS version.
- Separate License Type with () instead of / in License Name.
- Update version to 1.2.29
> Change the format of OSS mail

- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/domain/LicenseMaster.java
- src/main/java/oss/fosslight/domain/OssMaster.java
- src/main/java/oss/fosslight/service/impl/LicenseServiceImpl.java
- src/main/resources/oss/fosslight/repository/LicenseMapper.xml
- src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/oss/edit.jsp
- Fix a bug that is not searched as restriction: Non-Commercial Use Only in the License List.
- Fix a bug where nicknames were not loaded in automatic analysis.
- Fix the bug that the version is updated without adding a new OSS when copying OSS.
> Fix a bug that is not searched by restriction in the License List

- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/controller/LicenseController.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/domain/LicenseMaster.java
- src/main/java/oss/fosslight/domain/OssMaster.java
- src/main/java/oss/fosslight/service/NvdDataService.java
- src/main/java/oss/fosslight/service/impl/LicenseServiceImpl.java
- src/main/java/oss/fosslight/service/impl/SearchServiceImpl.java
- src/main/java/oss/fosslight/service/impl/StatisticsServiceImpl.java
- src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
- src/main/resources/oss/fosslight/repository/LicenseMapper.xml
- src/main/webapp/WEB-INF/views/admin/configuration/AJAX/searchConditionArea.jsp
- src/main/webapp/WEB-INF/views/admin/license/list-js.jsp
- src/main/webapp/WEB-INF/views/admin/oss/list-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/list-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/list.jsp
- src/main/webapp/WEB-INF/views/admin/project/list.jsp
- src/main/webapp/WEB-INF/views/template/layout/admin/header.jsp
- Fix the bug where the License List is not filtered by restriction.
- When adding a version in the new OSS save tab, modify it to load the latest version information.
- Update the Check model name message.
- User settings > If user isn't admin, add the "view my project/3rd party only" checkbox to the 3rd Party/Project List.
- Modify it to search when the List tab is opened.
- Change the batch size when downloading NVD data.
- Fix the bug of infinite loading when saving after uploading files from 3rd party.
If the OSS Name contains [ , ], [<], [>] symbols, a FORMAT Error occurs. (ex- OSS Name: 'Kerberos functionality from FundsXpress, INC.' Occurs when a comma (,) is included.)
> Fix the bug where the License List is not filtered by restriction

- build.gradle
> Update version to 1.2.30

- CHANGELOG.md
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/license/list-js.jsp
- src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/oss/list-js.jsp
- Fix the Unconfirmed Version OSS registration bug.
- In Check OSS Name, in case of npm, modify it to output package name.
- Modify the OSS /License List so that it does not search by default.
> Fix the Unconfirmed Version OSS registration bug

- src/main/java/oss/fosslight/api/controller/v1/ApiBatController.java
- src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/util/ExcelUtil.java
- Change the condition for displaying Binary Search in the API.
- Fix a bug that checks for duplicate model names in Distribution.
- When checking the name for npm in Check OSS Name, handle an exception for the case where @ is included.
> Check Oss Name > npm > registered OSS Name

- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/java/oss/fosslight/controller/SelfCheckController.java
- src/main/java/oss/fosslight/domain/Project.java
- src/main/java/oss/fosslight/repository/FileMapper.java
- src/main/java/oss/fosslight/repository/ProjectMapper.java
- src/main/java/oss/fosslight/service/impl/FileServiceImpl.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
- src/main/resources/oss/fosslight/repository/FileMapper.xml
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
- src/main/webapp/WEB-INF/views/admin/system/notice-js.jsp
- Fix the bug where the notification doesn't pop up.
- Fix the bug where files uploaded from Project are not deleted.
> Fix the bug where the notification doesn't pop up.

- build.gradle
- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/common/Url.java
- src/main/java/oss/fosslight/controller/ScannerController.java
- src/main/java/oss/fosslight/controller/SelfCheckController.java
- src/main/java/oss/fosslight/controller/VerificationController.java
- src/main/java/oss/fosslight/service/NvdDataService.java
- src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
- src/main/java/oss/fosslight/util/RequestUtil.java
- src/main/java/oss/fosslight/util/StringUtil.java
- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
- Change self-check unclear obligation message.
- Change NVD batch size.
- Don't delete draft comments when user clicks verify in Packaging.
- Add a log for cases where a null popup appears when clicking verify in Packaging.
- Fix mixed content error when entering url in self-check.
- upgrade mybatis-spring-boot-starter lib 1.3.5 to 2.2.2
> Change self-check unclear obligation message

- build.gradle
- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/java/oss/fosslight/domain/PartnerMaster.java
- src/main/java/oss/fosslight/repository/ProjectMapper.java
- src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/list-js.jsp
- Add vulnerability Score to 3rd party list.
- Fixed a bug where mail could not be sent (uncommented).
- Add the sheet name to be read by 3rd party. (OSS List, Open Source Software List)
- Update the pop-up message that appears when distribution rejects.
> Add vulnerability Score to 3rd party list

- CHANGELOG.md
- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/controller/SelfCheckController.java
- src/main/java/oss/fosslight/service/NvdDataService.java
- src/main/java/oss/fosslight/validation/T2CoValidationResult.java
* Self-check 
* If a red warning message appears according to the admin standard, mark it as Obligation: unclear.
* NVD > Change BatchExecutor size.
> Change the condition Obligation: unclear in self-check.

- CHANGELOG.md
- build.gradle
> Update version to 1.2.33

- src/main/java/oss/fosslight/common/CoConstDef.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/resources/static/robots.txt
- src/main/webapp/WEB-INF/views/admin/dashboard/list.jsp
- src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
- Fix the bug where OSS is renamed when copying and saving.
- Add robots.txt
- Remove the Strong tag from the Dashboard's Notice.
> Fix the bug where OSS is renamed when copying and saving.

- src/main/java/oss/fosslight/common/CommonFunction.java
Self-Check 
- Mark as obligation unclear for licenses that are not included in declared or detected licenses.
> Self-Check > Mark as obligation unclear for licenses that are not included in Declared or Detected licenses.

- src/main/java/oss/fosslight/common/CommonFunction.java
Self-check > Mark Obligation unclear for deactivate.
> Self-check > Mark Obligation unclear for deactivate.

- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/service/NvdDataService.java
- Fix a bug where Homepage could not be loaded for nickname when OSS Notice was issued.
- Fix nvd meta data job heap memory problem.
> Fix a bug where Homepage could not be loaded for nickname when OSS Notice was issued.

- build.gradle
> Update version to 1.2.34

- src/main/java/oss/fosslight/common/Url.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/domain/OssMaster.java
- src/main/java/oss/fosslight/util/ExcelUtil.java
- src/main/webapp/WEB-INF/tiles.xml
- src/main/webapp/WEB-INF/views/admin/oss/list.jsp
- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg.jsp
Signed-off-by: doggai10 <doggai77@gmail.com>
Register OSS in bulk by uploading Excel.
- Add a Bulk Registration button visible only to admin in the upper right corner of the OSS List.
1) example oss bulk excel form 
2) upload excel form on the oss bulk register page
3) register result 
first oss already registered on the data base.
second one has registered 
4) oss search result
> Register OSS in bulk by uploading Excel

- src/main/java/oss/fosslight/util/ExcelUtil.java
Separate the function to check header column in OSS Bulk.
> Separate the function to check header column in OSS Bulk

- src/main/java/oss/fosslight/common/Url.java
- src/main/java/oss/fosslight/controller/SessionController.java
- src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
- src/main/java/oss/fosslight/util/YamlUtil.java
- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
- Self-check > Notice tab > Don't print unconfirmed licenses
- Modify it to output to yaml even if version is null.
> Self-check > Notice tab > Don't print unconfirmed licenses

- src/main/resources/static/css/commonIframe.css
If user hover the mouse over the 'project name' in the 'project list', change it to a pointer icon.
#432
> Display pointer when mouse hovers on project name

- build.gradle
> Update version to 1.3.0

- CHANGELOG.md
- docker-compose.yml
Make it possible to set it as an env variable when running with docker-compose.
> Make it possible to set it as an env variable when running with docker-compose.

- src/main/java/oss/fosslight/common/CoConstDef.java
- src/main/java/oss/fosslight/domain/CoMail.java
- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
- src/main/resources/oss/fosslight/repository/T2UserMapper.xml
- src/main/resources/template/email/changeUserInfo.html
- Add a function to load user information from LDAP.
- If user information cannot be retrieved, change UseYN to N.
- Send an e-mail to the admin about the updated user information.
- Fix the bug that some licenses are not included in OSS Notice.
> Load user information from LDAP

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/resources/oss/fosslight/repository/OssMapper.xml
Fix bugs in `Check License`
- In case of Multi License, if the order is different, fix the bug in which a different license is determined.
Fix bugs in `Check OSS Name`.
- Fix the bug that Check OSS Name does not work for Unconfirmed OSS version.
Fix a bug where CVE-ID of OSS with OSS Version blank is not shown in OSS details.
> Fix bugs in Check License and Check OSS Name.

- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
Update OSS Type Mark > VersionDiff Service Transactional Declaration.
> Update OSS Type Mark > VersionDiff Service Transactional Declaration

- src/main/java/oss/fosslight/common/CoCodeManager.java
- src/main/java/oss/fosslight/controller/StatisticsController.java
- src/main/java/oss/fosslight/domain/CoCode.java
- src/main/java/oss/fosslight/domain/Statistics.java
- src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
- src/main/resources/oss/fosslight/repository/StatisticsMapper.xml
- Fix the bug that an error occurs when downloading the SPDX file.
- Change the OSS, License display format in statistics.
> Fix the bug that an error occurs when downloading the SPDX file

- build.gradle
> Update version to 1.3.2

- src/main/java/oss/fosslight/controller/ProjectController.java
Fix the bug where the request button disappears when packaging rejects.
> Fix the bug where the request button disappears when packaging rejects.

- build.gradle
> Update version to 1.3.3

- CHANGELOG.md
- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/java/oss/fosslight/domain/OssMaster.java
Mail > Print nickname changes when OSS version is changed.
> Mail > Print nickname changes when OSS version is changed.

- src/main/webapp/WEB-INF/views/admin/project/bom-js.jsp
When user clicks the cell of the ID column in the BOM, display the version-specific information popup.
> Display the version-specific popup when click the cell of the ID column in the BOM

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/resources/static/js/basic.js
Fix the error that the screen changes when user selects Reviewer from the User Setting, Project List, 3rd Party List.
> Fix the error that the screen changes when user selects Reviewer from the User Setting, Project List, 3rd Party List.

- build.gradle
> Update version to 1.3.4

- build.gradle
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/java/oss/fosslight/repository/OssMapper.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- OSS Details tab
- Fix bug that nickname is in different OSS when renaming OSS with multiple versions by clicking Rename.
- Mailing
- Fix bugs when sending OSS version additional mail.
> Fix a bug on clicking the Rename button

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/webapp/WEB-INF/views/admin/project/edit.jsp
When copying OSS and Project, try setting the name and version.
- Set the name as it is to be copied, and add `_Copied` to the version.
> When copying OSS and Project, try setting the name and version.

- src/main/java/oss/fosslight/controller/ProjectController.java
Fix bug where suffix is added twice in version
> Fix bug where suffix is added twice in version

- src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
- src/main/resources/oss/fosslight/repository/SelfCheckMapper.xml
- src/main/resources/oss/fosslight/repository/StatisticsMapper.xml
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
- After deleting the uploaded file in Self-check, change the error that occurs when saving.
- Change the modified query condition in statistics.
> After deleting the uploaded file in Self-check, change the error that occurs when saving.

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg.jsp
OSS Bulk Registration
- Fix the page not showing.
- Change the number displayed on one page to match your setting instead of 10.
- Save as Bulk registration and display success popup.
> Fix the page not showing in OSS Bulk

- src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
Fix the bug if the download location is null.
> Fix the bug if the download location is null

- build.gradle
> Update version to 1.3.6

- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
- Check OSS Name, License > Change the way you find links.
- Update Oss Type Flag Function.
> Check OSS Name, License > Change the way you find links

- src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
- src/main/java/oss/fosslight/common/Url.java
- src/main/java/oss/fosslight/util/ExcelUtil.java
Add model updates to the API.
- User can upload the Excel file in which the model list is created.
> Add model updates to the API

- build.gradle
> Update version to 1.3.7

- CHANGELOG.md
- README.md
- RELEASE_NOTES.md
> Add a release note

- RELEASE_NOTES.md
> Update the release note

- docs/README_kor.md
Add release note link to README.
> Add release note link to README

- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/java/oss/fosslight/service/ProjectService.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/edit.jsp
When copying a project, add a pop-up to choose which level to copy to.
However, the pop-up is displayed only for the project whose identification has been confirmed.
**Selectable steps to copy**
- Identification (Progress)
- Identification (Confirm)
- Packaging (Confirm)
> When copying a project, add a pop-up to choose which level to copy to.

- src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
- src/main/resources/oss/fosslight/repository/ApiProjectMapper.xml
API
- Update models regardless of status.
- Check write permission when calling api.
> API > Update models regardless of status

- src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
Fix the bug where the distribution site is changed when the model is updated with the api.
> Fix the bug where the distribution site is changed when the model is updated with the api

- src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
Fix the bug where model information cannot be found depending on the distribution site when updating model information with api.
> Fix the bug where the model cannot be found

- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
> Add validation error message

- build.gradle
> Update version to 1.3.8

- CHANGELOG.md
- src/test/java/oss/fosslight/controller/PackingRequestTest.java
Fix test errors during testing packaging.
> Fix test errors during testing packaging

- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
Change the UI for self-check upload.
> Change the UI for self-check upload

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/java/oss/fosslight/service/OssService.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
OSS Bulk registration > Fix the following bugs.
- A bug where OSS names are stored as duplicates.
- Existing nickname is deleted.
- OSS registration mail not sent.
> Fix OSS bulk registration bugs

- build.gradle
- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/java/oss/fosslight/repository/FileMapper.java
- src/main/java/oss/fosslight/service/FileService.java
- src/main/java/oss/fosslight/service/ProjectService.java
- src/main/java/oss/fosslight/service/impl/FileServiceImpl.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/resources/oss/fosslight/repository/FileMapper.xml
- src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
- src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
Fix the bug that the related filse of the base project is deleted when copying from the project.
> Fix the bug that the file is deleted when copying

- CHANGELOG.md
- RELEASE_NOTES.md
- docs/RELEASE_NOTES_kor.md
Add the release note Korean version.
> Add the release note Korean version.

- src/main/java/oss/fosslight/api/controller/v1/ApiProjectController.java
- src/main/java/oss/fosslight/util/ExcelUtil.java
API > Add parameters to model_update.
- AS-IS: Only spread sheets can be uploaded.
- TO-BE: Model list can be added as text.
> API > Add parameters to model_update

- .github/workflows/release-publish.yml
- Dockerfile
- build.gradle
- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/java/oss/fosslight/util/SPDXUtil2.java
- Update java version to 11.
- Remove spdx-rdf-store. (This package will be automatically installed as a dependency)
> Upgrade Java version to 11

- src/main/webapp/WEB-INF/views/template/layout/admin/header.jsp
> Update link of version

- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
Add check license button to Self-check.
> Add check license button to Self-check

- RELEASE_NOTES.md
- build.gradle
- docs/RELEASE_NOTES_kor.md
> Update version to 1.4.0

- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
Signed-off-by: Ji Seungmin <cswcsm02@gmail.com>
Change tab name from "oss List" to "OSS List"
> Change 'oss List' to 'OSS List'.

- src/main/webapp/WEB-INF/views/admin/selfCheck/list-js.jsp
Change the column name to CVSS Score to Vulnerability in Self Check Tab
> Change the column name to CVSS Score to Vulnerability in Self Check Tab

- src/main/webapp/WEB-INF/views/admin/selfCheck/list-js.jsp
Signed-off-by: MyunghyungNero <mh1kim0910@gmail.com>
Change CVSS Score to Vulnerability in Self Check Tab.
> Change CVSS Score to Vulnerability in Self Check Tab

- build.gradle
- src/main/java/oss/fosslight/common/CorsFilter.java
- src/main/resources/application.properties
- src/main/resources/oss/fosslight/repository/NvdDataMapper.xml
- Update Spring boot version 2.1.7 to 2.6.8.
- Fix the NVD Sync error.
```
2022-06-10 01:05:24.451 17273726 [taskScheduler-1] ERROR [NvdDataService.java, executeNvdDataSync():96]     -
2 ### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: (conn=6397) Duplicate entry 'dbi-1.40' for key 'PRIMARY'
3 ### The error may exist in oss/fosslight/repository/NvdDataMapper.xml
4 ### The error may involve defaultParameterMap
5 ### The error occurred while setting parameters
```
> Update Spring boot version 2.1.7 to 2.6.8

- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/java/oss/fosslight/repository/OssMapper.java
- src/main/java/oss/fosslight/service/impl/ApiProjectServiceImpl.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/java/oss/fosslight/util/ExcelUtil.java
- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/binAndroid-js.jsp
- Shorten the long loading time when viewing the OSS List.
- BIN (Platform) Tab (experimental)
- Show popup for sheet without required column.
- Change the Notice column value OK condition. (Find the file regardless of path.)
- Notice Supplement Change possible conditions.
> Shorten the long loading time when viewing the OSS List.

- RELEASE_NOTES.md
- build.gradle
- docs/RELEASE_NOTES_kor.md
> Update the release notes

- CHANGELOG.md
- src/main/java/oss/fosslight/service/impl/ApiProjectServiceImpl.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
- API > Update bom compare format.
- Delete unnecessary paths in the packaging file list.
- Update download location and homepage > Apply the same link check method.
> API > Update bom compare format

- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/java/oss/fosslight/service/impl/ApiProjectServiceImpl.java
- src/main/resources/template/email/ossInfo.html
- src/main/resources/template/email/ossModify.html
- src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
- src/main/webapp/WEB-INF/views/admin/project/edit.jsp
- Update UI (3rd party/Basic Information) : expand the width (Creator/Division/Reviewer)
- API > bom compare > changed data format
- Add images for oss type image.
> Update UI (Creator/Division/Reviewer) - change the width

- RELEASE_NOTES.md
- build.gradle
- docs/RELEASE_NOTES_kor.md
- src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
Update download location and homepage > same link check condition.
> Update download location and homepage > same link check condition

- CHANGELOG.md
- src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
Add Model Information table to project's basic information tab.
> Add Model Information table

- src/main/resources/static/css/commonIframe.css
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
Signed-off-by: 70825 <hello70825@gmail.com>
Change the message when selecting URL
> Change the message when selecting URL

- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
When copying the project, make a copy of whether the notice has been modified.
> Copy whether notice has been modified or not

- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
Fix the bug where uploaded files are not visible
> Fix the bug where uploaded files are not visible

- db/initdb.d/fosslight_create.sql
- src/main/java/oss/fosslight/common/CoConstDef.java
- src/main/webapp/WEB-INF/views/admin/system/user-js.jsp
Hide email according to system setting in user management option of system.
> Hide user email as per option

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
- src/main/resources/oss/fosslight/repository/PartnerMapper.xml
- src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
- Fix the bug where sorting by column is not possible in the 3rd party list.
- Do not save after modifying OSS name and nickname at the same time in OSS detailed information.
> Fix the bug where sorting by column is not possible in the 3rd party list

- build.gradle
> Update version to 1.4.4

- CHANGELOG.md
- src/main/resources/oss/fosslight/repository/DashboardMapper.xml
Hide the dropped project list in Opened Jobs of Dashboard
> Hide the dropped project list in Opened Jobs of Dashboard

- src/main/resources/oss/fosslight/repository/DashboardMapper.xml
Show the project list in Opened Jobs of Dashboard when user is not admin
> Show the project list in Opened Jobs of Dashboard when user is not admin

- src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
- src/main/java/oss/fosslight/util/YamlUtil.java
- src/main/resources/oss/fosslight/repository/PartnerMapper.xml
- Fixed the bug where sorting in 3rd party list works inproper in case of general user.
- Change yaml file format when oss list is exported as yaml file.
> Change yaml file format when oss list is exported as yaml

- Dockerfile
Make it run as docker on Mac M1.
> Update Dockerfile for Mac M1

- RELEASE_NOTES.md
- build.gradle
- docs/RELEASE_NOTES_kor.md
- src/main/java/oss/fosslight/controller/DownloadProcController.java
- src/main/java/oss/fosslight/controller/ImageViewController.java
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
Update BAT > show GUI report icon.
> (Experimental) Update BAT > show GUI report icon

- src/main/java/oss/fosslight/common/Url.java
- src/main/java/oss/fosslight/controller/PartnerController.java
- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/java/oss/fosslight/domain/PartnerMaster.java
- src/main/java/oss/fosslight/repository/ProjectMapper.java
- src/main/java/oss/fosslight/service/PartnerService.java
- src/main/java/oss/fosslight/service/ProjectService.java
- src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
- src/main/resources/static/css/commonIframe.css
- src/main/resources/static/js/basic.js
- src/main/webapp/WEB-INF/views/admin/oss/ossAutoAnalysispopup.jsp
- src/main/webapp/WEB-INF/views/admin/partner/list-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/list.jsp
- src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/list.jsp
Add a button "Change division" to the Project List.
> Add the function to change division

- RELEASE_NOTES.md
- build.gradle
- docs/RELEASE_NOTES_kor.md
- src/main/java/oss/fosslight/util/ExcelUtil.java
- src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
Fix the error that occurs when clicking Check OSS Name in 3rd party.
If the license name is chenaged, fix to not record comments.
> Fix the error that occurs when clicking Check OSS Name in 3rd party

- src/main/webapp/WEB-INF/views/admin/license/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
> Change nickname input position of OSS List, License List when Add button is clicked

- src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
- src/main/webapp/WEB-INF/views/admin/compliance/modelStatus-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/list-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/list.jsp
- src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/list.jsp
- Fix the bug where search terms are entered during change division.
- (Experimental) Fix the bug that Compliance status is not exported.
> Fix the bug where search terms are entered during change division

- src/main/resources/messages/message_en.properties
- src/main/resources/messages/message_ko.properties
- src/main/webapp/WEB-INF/views/admin/system/configuration.jsp
Add guide comment that is about when the system setting are reflected in Configuration tab
#595
> Add guide comment in Configuration

- src/main/webapp/WEB-INF/views/admin/common/gridCommonFn.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/bin-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/src-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
User can move to a cell when they double-click that cell in oss table
> Move to a cell what I double-click

- build.gradle
- src/main/resources/messages/message_en.properties
- src/main/resources/messages/message_ko.properties
- src/main/resources/static/css/commonIframe.css
- src/main/webapp/WEB-INF/views/admin/common/gridCommonFn.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
- src/main/webapp/WEB-INF/views/admin/project/bin-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/binAndroid-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/src-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/system/configuration.jsp
- Add guide comment in configuration.
- Move to a cell what I double-click on OSS Table.
- Increase the length of the name field.
- Add priority to the status of project list.
> Release the contributed commits 

- .github/workflows/pull-request.yml
- .github/workflows/release-publish.yml
- CHANGELOG.md
- src/main/webapp/WEB-INF/views/admin/project/edit.jsp
- src/main/webapp/WEB-INF/views/template/layout/admin/header.jsp
- Caching Dependencies to speed.
- Increase the length of project's name field.
- Show the user's name when mouse hover it.
> Release the contributed commits

- src/main/java/oss/fosslight/common/AjaxSessionTimeoutFilter.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/service/impl/VulnerabilityServiceImpl.java
- src/main/resources/static/css/commonIframe.css
- src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
- src/main/webapp/WEB-INF/views/admin/project/bin-js.jsp
- Change the CVSS Score for sending Vulnerability alerts from 9.0 to 8.0.
- Fix the bug that the page does not load after clicking Check License in 3rd Party.
- Fix the bug where you can delete the uploaded file in the BIN tab.
- Modify the position of the comment edit button so that it does not overlap other buttons.
> Change the CVSS Score for sending Vulnerability alerts from 9.0 to 8.0

- db/initdb.d/fosslight_create.sql
- src/main/java/oss/fosslight/config/CustomAuthenticationProvider.java
- src/main/java/oss/fosslight/config/SecurityConfig.java
- src/main/java/oss/fosslight/service/T2UserService.java
- src/main/java/oss/fosslight/service/impl/T2UserServiceImpl.java
- src/main/resources/messages/message_en_US.properties
- src/main/resources/messages/message_ko_KR.properties
- src/main/webapp/WEB-INF/views/admin/configuration/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/configuration/edit.jsp
- src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
- src/main/webapp/WEB-INF/views/session/login.jsp
- src/main/webapp/WEB-INF/views/template/layout/admin/header.jsp
Skip registration step when using LDAP
- If LDAP is used, "log in" is possible without registration.
> Skip registration step when using LDAP

- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
When renaming to another OSS while deleting OSS, check License.
> When renaming to another OSS while deleting OSS, check License

- CHANGELOG.md
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/edit.jsp
- src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
- src/main/webapp/WEB-INF/views/admin/vulnerability/list-js.jsp
- Fix the bug of infinite loading when searching for cve ID with -.
- Check OSS Name > Change it to work for rows with OSS Name of - as well.
- Fix the bug where the division of the project is not saved as N/A.
- Correct the Priority typo in the Status tooltip of the Project List.
> Fix the bug of infinite loading when searching for cve ID with -

- src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
- src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
- src/main/webapp/WEB-INF/views/admin/vulnerability/vulnpopup.jsp
This PR add export feature to vulnerability popup #579.
There is no feature to export vulnerability data in popup.
Users can export vulnerability data in popup.
https://user-images.githubusercontent.com/33149791/181556318-1843c87f-ef90-4087-a5cb-4b40d6235f98.mov
Vulnerability popup uses repository method `VulnerabilityService.getVulnListByOssName` unlike vulnerability tab using `vulnerabilityService.getVulnerabilityList`.
So i add new case ‘vulnerabilityPopup’ to use `VulnerabilityService.getVulnListByOssName` to export datas in popup. 
Vulnerability excel template requires `PUBI_DATE` column to show 'Published Date'.
Unlike `vulnerabilityMapper.selectVulnerabilityExportList`, 
`VulnerabilityMapper.getVulnListByOssName` is not selecting PUBI_DATE. 
So i add selecting `PUBI_DATE`  column …
> Add export feature to vulnerability popup

- build.gradle
> Update version to 1.4.9

- CHANGELOG.md
- src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
- src/main/resources/oss/fosslight/repository/PartnerMapper.xml
- Fix bugs that are invisible even as Watchers in the 3rd party list.
- Fix the bug where the warning message is duplicated when exporting in self-check.
> Fix bugs that are invisible even as Watchers in the 3rd party list

- src/main/java/oss/fosslight/controller/SPDXDownloadController.java
- src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
Fix SPDX download error in Self-check > Notice.
> Fix SPDX download error in Self-check > Notice

- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
- src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
Add a Yaml button to 3rd Party, Project, Self-check.
- Click the Yaml button to download OSS Table in yaml format.
> Add a Yaml button to 3rd Party, Project, Self-check

- src/main/webapp/WEB-INF/views/admin/project/bin-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/src-js.jsp
Sheet name that is automatically checked when uploading a file in Project Identification.
- AS-IS: 
- SRC tab : SRC
- BIN tab : BIN 
- TO-BE:
- SRC Tab : Names starting with SRC
- BIN Tab : Names starting with BIN
> Change the sheet name that is checked when uploading a file in Project Identification

- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
- Fix the bug where the link changes from Check License to https://https://.
- In Self-check > Notice, fix the bug where licenses are not merged by OSS name and version.
> Fix the bug where the link changes from Check License to https://https://

- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
- src/main/java/oss/fosslight/service/impl/VulnerabilityServiceImpl.java
- src/main/resources/oss/fosslight/repository/VulnerabilityMapper.xml
- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
- src/main/webapp/WEB-INF/views/admin/partner/view-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/view.jsp
- src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/edit.jsp
- src/main/webapp/WEB-INF/views/admin/project/view-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/view.jsp
- New 
- Add 'Share URL' Button in Project, 3rd Party.
- Bug Fix
- Self-check > Notice > 
- Copyleft OSS Table is created when Hide OSS version is checked.
- Fix the bug where the copyright of row, which is an unconfirmed open source | version, is not visible
- Vulnerability List > Fix bug where nickname is not displayed when searching by OSS name.
- Fix the bug where Division is not output when leaving a comment when changing Division.
> Add 'Share URL' Button in Project, 3rd Party

- src/main/java/oss/fosslight/common/Url.java
- src/main/java/oss/fosslight/controller/PartnerController.java
- src/main/java/oss/fosslight/repository/PartnerMapper.java
- src/main/java/oss/fosslight/service/PartnerService.java
- src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
- src/main/resources/oss/fosslight/repository/PartnerMapper.xml
- src/main/resources/static/css/commonIframe.css
- src/main/resources/static/js/basic.js
- src/main/resources/static/js/basic_editor.js
- src/main/webapp/WEB-INF/views/admin/license/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
- src/main/webapp/WEB-INF/views/admin/partner/view-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/view.jsp
- src/main/webapp/WEB-INF/views/admin/project/AJAX/commentArea.jsp
- src/main/webapp/WEB-INF/views/admin/project/AJAX/commentPopup.jsp
- src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/edit.jsp
- src/main/webapp/WEB-INF/views/admin/project/view-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/view.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
* Change [PRJ-ID] or [3rd-ID] text to linkable text 
Pattern of text : [PRJ-ID] or [3rd-ID]
Location of changing link :
- Comment History(Project, 3rd Party, OSS, License, Self-check > Comment)
- Project > Basic Information > Additional Information
- 3rd party > Description
- email
Click the link :
if the user has edit permission, display editable basic information/3rd party page.
if not, display readonly basic information/3rd party page.
* When access to "Share URL" link, 
if the user has edit permission, display editable basic information/3rd party page.
if not, display readonly basic information/3rd party page.
> Change [PRJ-ID] or [3rd-ID] text to linkable text

- src/main/resources/static/js/basic.js
When input PRJ-ID/prj-ID/3RD-ID/3rd-ID, add link tag with text.
> Change regular expression of project link

- src/main/webapp/WEB-INF/views/admin/project/edit.jsp
Fix bug where watcher row is duplicated in Project basic information when user has permission.
> Fix bug where watcher row is duplicated in project basic information

- src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
Add logic to validate for download location from input data.
If download location has wrong format, display alert message.
> Add logic to validate for download location from input data

- src/main/java/oss/fosslight/domain/CoMailManager.java
If there are lists with duplicate oss names, version and license name, combine them into one.
> Remove duplicated oss list in 3rd party mail

- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/controller/PartnerController.java
- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
- src/main/resources/messages/message_en.properties
- src/main/resources/messages/message_ko.properties
- src/main/webapp/WEB-INF/views/admin/partner/list-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/list.jsp
- src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
- Check user permission when changing divisions.
- Do not allow users who do not have write permission on the project to change the division.
- Fix the bug where the "Please check input data format" pops up when the download location is null.
- Save it regardless of the download location format.
> Check user permission when changing divisions.

- db/initdb.d/fosslight_create.sql
- src/main/java/oss/fosslight/common/CoConstDef.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
- Modify it to look for www.npmjs.com/ as well as www.npmjs.org.
- Check OSS Name > Fix the bug that the recommended OSS name cannot be printed if it is not stored in the DB for the npm link.
- Fix link url validation function.
- Change it so that Save and Request are possible even if user enters a link format that is not supported.
> Add the NPM link pattern

- src/main/webapp/WEB-INF/views/admin/compliance/3rdList.jsp
- src/main/webapp/WEB-INF/views/admin/compliance/modelStatus.jsp
- src/main/webapp/WEB-INF/views/admin/license/list.jsp
- src/main/webapp/WEB-INF/views/admin/oss/list.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
- src/main/webapp/WEB-INF/views/admin/partner/list.jsp
- src/main/webapp/WEB-INF/views/admin/project/bom-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
- src/main/webapp/WEB-INF/views/admin/project/list.jsp
- src/main/webapp/WEB-INF/views/admin/project/src-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/verification.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/list.jsp
- src/main/webapp/WEB-INF/views/admin/vulnerability/list.jsp
Remove all buttons at the bottom of the table.
- OSS List
- License List
- Vulnerability 
- Self-check List
- Compliance Status
- Model OSC Status
- 3rd Party Status
- 3rd Party
- List
- 3rd Party tab
- Project
- List
- Identification 
- Packaging
> Remove buttons at the bottom of the table.

- src/main/webapp/WEB-INF/views/admin/system/binaryDataHistory.jsp
- src/main/webapp/WEB-INF/views/admin/system/user.jsp
Change buttons to be top of the table in Binary DB, System > User management
> Change buttons to be top of the table in Binary DB, System > User management

- src/main/resources/static/css/jqgrid4.7/ui.jqgrid.css
Add search icon in filter cell of the table as below.
> Add "search icon" in filter cell of table

- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
edit and multiselct are added to ossBulkRegRows
Signed-off-by: Ji Seungmin <cswcsm02@gmail.com>
> Add editable and selectable to ossBulkRegRows

- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit.jsp
Self-check > Add SPDX as well as FOSSLight Report to the export button download.
> Self-check > Add SPDX as well as FOSSLight Report to the export button download

- src/main/webapp/WEB-INF/views/admin/configuration/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/view.jsp
- src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/view.jsp
If project's division is set as unused division(Use YN flag is N), display division of basic information as unused division.
> Display division information even if Use YN flag of division is N

- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
Fix bug where CVE-ID is displayed as duplicate in OSS details tab.
> Fix bug where CVE-ID is displayed as duplicate in OSS details tab

- src/main/webapp/WEB-INF/views/admin/common/gridCommonFn.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
- src/main/webapp/WEB-INF/views/admin/partner/list-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/edit.jsp
- src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
- When click "+" button, insert new row at the top of the table
- Show "export" button in 3rd party regardless of permission
- Bug fix : click "change division" button > click "cancel" button > click "change division" button again
-  display division list in drop down menu
- Change division information in project basic information and 3rd party when user has permission
> When click "+" button, insert new row at the top of the table

- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
Fix the bug where the license flag is not saved when saving OSS.
> Fix the bug where the license flag is not saved when saving OSS

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
Signed-off-by: MoonDD99 <mjh991016@naver.com>
Auto upload unconfired version/oss data to oss bulk registeration pop up from project identification SRC and BIN
- The screenshot that follows is oss bulk registration pop up from Project identification
> Auto upload identification invalid data to oss bulk registration

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
Automatically load unconfirmed version/oss into bulk registration
> Automatically load unconfirmed version/oss into bulk registration

- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
> Send OSS save failed return code differently

- src/main/java/oss/fosslight/controller/ProjectController.java
Project > Identification > 3rd Party Tab >
When Save is clicked, leave a comment on the history of changing nickname.
> Project > 3rd Party tab > Leave a comment on the history of changing nickname.

- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
Do not save automatically when division is changed.
When click the save button, save division information
> When division information is changed, do not save automatically.

- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
- This PR move OSS bulk button of SRC, BIN tab to BOM tab (SRC, BIN buttons removed)
> Move OSS bulk button to BOM tab

- src/main/java/oss/fosslight/domain/OssComponents.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
Fix the bug where the license written as nickname does not change to license name when save is clicked.
> Fix the bug where the license written as nickname does not change to license name when save is clicked

- src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
- src/main/webapp/WEB-INF/views/admin/project/bom-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
If user clicks Export Button, then user can select SPDX spreadsheet, RDF, TAG, JSON, YAML file as well as  FOSSLight Report
> Support SPDX download in bom tab

- src/main/java/oss/fosslight/domain/OssComponents.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
- Fix the bug where License does not change to SPDX-ID in Project> 3rd Party tab.
> Fix a bug that occurs when saving to 3rd party tab in project

- LICENSES/AGPL-3.0.txt
- LICENSES/LicenseRef-3rd_party_licenses.txt
> Add license text files

- Dockerfile
Add license text files to docker image.
> Add license text files to docker image

- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
In comment mail, activate project/3rd party link (PRJ-ID, 3RD-ID)
> In comment mail, activate project/3rd party link 

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/util/ExcelUtil.java
- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
> Show detail failure messages in OSS bulk feature. (#669)

- src/main/resources/application.properties
- src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
Fix the broken identification ui bug.
> Fix the broken identification ui bug

- src/main/resources/template/email/changeUserInfo.html
- src/main/resources/template/email/commentWithProjectInfo.html
- src/main/resources/template/email/projectInfo.html
- src/main/resources/template/email/watcherInvated.html
I changed some letters for unity
- User information → User Information
- date → Date
- Operating system → Operating System
> Fix typo email template 

- src/main/resources/template/email/changeUserInfo.html
- src/main/resources/template/email/commentWithProjectInfo.html
- src/main/resources/template/email/projectInfo.html
- src/main/resources/template/email/watcherInvated.html
- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
- Email Template > correct the typo.
- OSS Bulk Registration
- Fix a bug where copyright is not added.
- Add triming logic to list attributes
> OSS Bulk Registration > Fix a bug where copyright is not added

- src/main/java/oss/fosslight/controller/OssController.java
Fix the compilation error - cannot find symbol.
> Fix the compilation error - cannot find symbol

- src/main/java/oss/fosslight/common/Url.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/java/oss/fosslight/domain/OssMaster.java
- src/main/webapp/WEB-INF/views/admin/oss/list-js.jsp
- src/main/webapp/WEB-INF/views/admin/system/sentMail-js.jsp
- src/main/webapp/WEB-INF/views/template/layout/admin/header.jsp
Change the link of OSS Name (version) in the OSS registration/modification mail so that the window that searches for the OSS Name in the OSS List appears.
> Change the link of OSS Name (version) in OSS registration/modification mail.

- .github/workflows/release-publish.yml
I added Slack notification bot to notice release results.
> Add Slack notification bot

- .github/workflows/release-publish.yml
Add Slack notification bot to workflow.
> Add Slack notification bot to workflow

- .github/workflows/release-publish.yml
I updated workflow to add multiple tags(latest, release version) when building the image.
> Add latest tag to docker image

- .github/workflows/release-publish.yml
- CHANGELOG.md
Add latest tag to docker image.
> Add latest tag to docker image.

- .github/workflows/release-publish.yml
- Dockerfile
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/service/OssService.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/bin-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/binAndroid-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/src-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
> Fix grid data save function

- src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
- src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/edit.jsp
- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
- src/main/webapp/WEB-INF/views/admin/project/verification-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/verification.jsp
- Fix the bug where it is not merged when exporting in BOM tab.
- Change the notation at the top of each Project tab to `"Project Name (version)"`.
> Fix the bug where it is not merged when exporting in BOM tab.

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
- src/main/webapp/WEB-INF/views/admin/project/3rd-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
- Remove the buttons at the bottm of the table in project > identification > 3rd party
- Change the link in registration and changing oss information mail
- When copying the project, set division information as creator's division
- Fix the bug when copying the project with packing confirm status
- Fix the bug when searching binary name in project list
- Fix the bug when saving oss information which has detected license
- Add search filter in project > identification > 3rd party
> Fix link in registration mail OSS Name (version)

- .github/workflows/stale.yml
Create stale.yml to close stalled issues and prs.
> Create stale.yml to close stalled issues and prs

- src/main/java/oss/fosslight/common/Url.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/validation/custom/T2CoOssValidator.java
- src/main/resources/messages/validation.properties
- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
OSS Bulk Registration > Show warning messages.
- Duplicated name
- Duplicated nick
- Unconfirmed license
- This field is required (OSS name, Declared licenses)
> OSS Bulk Registration > Show warning messages

- src/main/java/oss/fosslight/common/Url.java
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/validation/custom/T2CoOssValidator.java
- src/main/resources/messages/validation.properties
- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
Signed-off-by: Dongwon Kim <freshtuna@kakao.com>
OSS Bulk Registration > Show warning messages.
> OSS Bulk Registration > Show warning messages (#715)

- .github/workflows/stale.yml
Remove the part that adds a label to an issue so that only old PRs are automatically closed.
> Remove issue auto-close

- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
Add the file name for apex in NOTICE.
- _compressed.apex
> Add the file name for apex in NOTICE

- .github/workflows/stale.yml
Separated messages of issue and pull request.
**AS-IS**
```yml
STALE_MESSAGE: |
This has been automatically marked as stale because it hasn't had any recent activity. 
It will be closed in 5 days if no further activity occurs.
CLOSE_MESSAGE: |
Closing this because it has been inactive for 5 days since being marked as stale.
```
**TO-BE**
```yml
STALE_PR_MESSAGE: |
This PR has been automatically marked as stale because it hasn't had any recent activity. 
It will be closed in 5 days if no further activity occurs.
CLOSE_PR_MESSAGE: |
This PR was closed because it has been inactive for 5 days since being marked as stale.
CLOSE_ISSUE_MESSAGE: |
This issue was closed because it has been inactive for 5 days since being marked as stale.
```
> Separate messages of issue and pull request

- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
Project List >
Fix the bug that other projects are viewed even if user checked 'View my project only'.
> Project List > Fix bugs related to View my project only

- src/main/java/oss/fosslight/common/CommonFunction.java
Add file extraction tag in Notice of Android.
> (Experimental) Add file extraction tag in Notice of Android

- src/main/resources/static/js/basic.js
- src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
Project List
- Fix a bug that caused a permission error when clicking on an empty space in Identification.
- Automatically complete the model name when 3 letters are entered among the search conditions.
> Project List > Fix a bug that caused a permission error when clicking on an empty space in Identification.

- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/java/oss/fosslight/domain/Project.java
- src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
- src/main/java/oss/fosslight/util/ExcelUtil.java
- src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
- src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
- src/main/webapp/WEB-INF/views/admin/statistics/statisticspopup.jsp
The following bugs were fixed.
- Statistics > Most used oss  > When sorting is clicked, the total row is included and sorted, and a new total row is added 
- Packaging > Notice > If OSS Name is -, Permissive license is printed on Copyleft.
- Project List > Without view permission, status can be changed.
- Check OSS Name > URL is added even though redirect url is "". 
- 'This Model Name is already exists.' is displayed indicating that the model is not duplicated in the model list.
> Fix issuance of notice for permissive license

- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/config/AppConstBean.java
- src/main/java/oss/fosslight/config/CustomAuthenticationProvider.java
- src/main/java/oss/fosslight/config/CustomWebAuthenticationDetails.java
- src/main/java/oss/fosslight/config/CustomWebAuthenticationDetailsSource.java
- src/main/java/oss/fosslight/config/SecurityConfig.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
- src/main/java/oss/fosslight/service/impl/T2UserServiceImpl.java
- src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
- src/main/resources/messages/message_en.properties
- src/main/resources/messages/message_ko.properties
- src/main/webapp/WEB-INF/views/admin/statistics/statisticspopup.jsp
- src/main/webapp/WEB-INF/views/admin/statistics/view-js.jsp
- src/main/webapp/WEB-INF/views/admin/statistics/view.jsp
- Add check email when login new user.
- Check the email when logging in, in case the user has the same id or a different email.
- Add apex file extension to find.
- Merge nickname of auto analysis result and nickname of the latest registered oss.
- Change special charaters as ascii code when verify process of packaging.
- Statistics
- Add a search button.
- Display popup by division when click the most used oss/license graph.
- When saving oss data in self-check, convert oss name without case sensitive.
> Add check email when login new user

- build.gradle
- db/initdb.d/fosslight_create.sql
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
- src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
Check OSS Name
- Add Android format(android.googlesource.com/platform/) to change oss name.
- Display "Invalid download location" when download location is not accessible.
- Change the button name
- Add URL, Recommened Nickname -> Add URL, Nickname based on URL
> Add Android format(android.googlesource.com/platform/) to change oss name.

- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- Add defensive code in check oss name
> Add defensive code in check oss name

- src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
When export the specific oss name of vulnerablity, append oss name to exported file name.
> When export the specific oss name of vulnerablity, append oss name to exported file name 

- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/service/NvdDataService.java
- src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
- When add new 3rd party project, save description.
- When url connection exception is occurred, add retry connecting code.
- After change license by using "check oss license", fix to reload the main page properly.
- Display the latest oss information which has nickname or oss name of auto analysis result.
> Display the latest oss information which has nickname or oss name of auto analysis result 

- src/main/java/oss/fosslight/controller/OssController.java
- src/main/webapp/WEB-INF/views/admin/oss/syncpopup.jsp
When sync oss, it is also possible to update only comment.
> When sync oss, it is also possible to update only comment.

- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/java/oss/fosslight/validation/custom/T2CoProjectValidator.java
- src/main/resources/messages/validation.properties
Display "Required oss name" warning message under the specific condition as below
- oss name : "-"
- license : source obligation is included
> Display "Required oss name" warning message 

- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
Fix bug where license is not merged in BOM if it is blank.
> Fix bug where license is not merged in BOM if it is blank

- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/java/oss/fosslight/domain/T2Users.java
- src/main/resources/oss/fosslight/repository/T2UserMapper.xml
LDAP > Modify the updated date to be displayed in user information when sending mail.
> LDAP > Modify the updated date to be displayed in user information when sending mail.

- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
Fix license name saved redundantly.
> Fix license name saved redundantly

- .github/dependabot.yml
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
Configure Dependabot for GitHub Actions.
> Configure Dependabot for GitHub Actions

- src/main/java/oss/fosslight/config/CustomAuthenticationProvider.java
Fix a bug that caused an error when the password was incorrect when setting LDAP.
> LDAP > Fix a bug that caused an error when the password was incorrect.

- LICENSES/LicenseRef-3rd_party_licenses.txt
- src/main/java/oss/fosslight/controller/OssController.java
- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/java/oss/fosslight/domain/OssMaster.java
- src/main/java/oss/fosslight/repository/OssMapper.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/util/ExcelUtil.java
- src/main/resources/oss/fosslight/repository/OssMapper.xml
- src/main/webapp/WEB-INF/views/admin/partner/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/edit-js.jsp
- Fix bug with create project for OSS Notice.
- Update license text for 3rd party software.
> Fix bug with create project for OSS Notice

- LICENSES/LicenseRef-3rd_party_licenses.txt
> Update 3rd party licenses

- src/main/java/oss/fosslight/service/ProjectService.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
When exporting BOM, output "3rd-{3rd Party Name}" in the **From** column in case of 3rd party.
> Print partner name in excel BOM

- src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
Fix bug with previously generated OSS notices.
> Fix bug with previously generated OSS notices

- src/main/java/oss/fosslight/service/impl/FileServiceImpl.java
Remove all files and folder related to compressed notice file.
> Remove all files and folder related to compressed notice file.

- src/main/java/oss/fosslight/common/Url.java
- src/main/java/oss/fosslight/controller/LicenseController.java
- src/main/java/oss/fosslight/service/LicenseService.java
- src/main/java/oss/fosslight/service/impl/LicenseServiceImpl.java
- src/main/java/oss/fosslight/validation/custom/T2CoLicenseValidator.java
- src/main/webapp/WEB-INF/views/admin/license/licenseBulkReg-js.jsp
Save multiple licenses at once.
> License Bulk Registration

- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
Fix the bug - fail to load autoanalysis result because of nullpointer exception.
Fix the syntax error in sql query.
> Fix the bug - fail to load autoanalysis result  

- src/main/resources/template/notice/notice.html
- src/main/resources/template/notice/notice_sks.html
- src/main/resources/template/notice/selfcheck_notice.html
In NOTICE.html template, add property rel = "noreferrer noopener" when using <a> tag with target="_blank"
> Fix the vulnerability issue in NOTICE.html

- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/oss/ossBulkReg-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/edit.jsp
- OSS Bulk Registration is possible in 3rd party
- Check License name > display license name with recommended warning message
> In 3rd party, "OSS Bulk Registration" is possible.

- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/util/ExcelUtil.java
- Fix release date data check function when model list upload.
- Update the nuget url.
> Fix release date data check function when model list upload

- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/java/oss/fosslight/domain/Project.java
- src/main/java/oss/fosslight/domain/ProjectIdentification.java
- src/main/java/oss/fosslight/repository/ProjectMapper.java
- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/java/oss/fosslight/service/impl/PartnerServiceImpl.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
- src/main/resources/template/notice/notice.txt
Bug fix
- Fix the bug where model category is not displayed properly in email
- Exclude "check license" if only one of the multi license including all permissive license is entered.
- When deleting project, remove distribution information from distribution site.
Refactoring, Maintenance
- Improve the speed of loading oss table.
> Improve the speed of loading oss table.

- src/main/java/oss/fosslight/api/controller/v1/ApiSelfCheckController.java
- src/main/java/oss/fosslight/service/NvdDataService.java
- src/main/java/oss/fosslight/service/impl/AutoFillOssInfoServiceImpl.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
Bug fix
- Bug fix where uploading csv file via self-check oss-report-selfcheck API.
- Even if download location is empty, "check license name" function works properly when the oss matched with name and version is existed.
- In excluded list where oss/license name is empty, "save and merge" works properly in bom tab.
> Bug fix where uploading csv file via self-check oss-report-selfcheck API.

- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/resources/messages/message_en.properties
- src/main/resources/messages/message_ko.properties
- Bug fix where generating oss name of android platform in "Check OSS Name".
- Bug fix where BOM tab has not merged when project is copied with "packaging confirm" status.
- Change comment message when oss name has been changed by "Check OSS Name".
> Bug fix where generating oss name of android platform in "Check OSS Name"

- src/main/resources/oss/fosslight/repository/PartnerMapper.xml
- src/main/webapp/WEB-INF/views/admin/partner/list.jsp
Signed-off-by: SEOKHO KIM [kim76744dev@gmail.com]
Issue #816 
Add description search on 3rd party list
- Add Description textarea
- Add query
> Add 3rd party description search

- RELEASE_NOTES.md
- docs/RELEASE_NOTES_kor.md
> Update release note (v1.5.1)

- src/main/java/oss/fosslight/common/Url.java
- src/main/java/oss/fosslight/controller/NoticeController.java
- src/main/java/oss/fosslight/controller/ProcessGuideController.java
- src/main/webapp/WEB-INF/views/template/layout/admin/template.jsp
Fix Typo ```publishedt``` to ```published```
> Fix a typo from 'publishedt' to 'published'

- src/main/java/oss/fosslight/controller/ScannerController.java
Fix a typo from scannServiceUrl to scanServiceUrl
resolved: #891
> Fix a typo from scannServiceUrl to scanServiceUrl

- src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
- Removed deprecated "WITH" option
- fix issue on this link <https://github.com/fosslight/fosslight/issues/808>
> Removed deprecated "WITH" option - #808 

- src/main/java/oss/fosslight/config/WebConfig.java
- src/main/java/oss/fosslight/controller/CommentController.java
- src/main/java/oss/fosslight/controller/LicenseController.java
- src/main/java/oss/fosslight/controller/SelfCheckController.java
- src/main/java/oss/fosslight/controller/UserController.java
I removed unused import statements in src/main/java/oss/fosslight/config, controller
Then, I checked that project works well.
> Remove unused import statements

- src/main/java/oss/fosslight/controller/AdviceController.java
- src/main/java/oss/fosslight/controller/CommentController.java
Delete unnecessary code in controller, such as empty else statements.
This is my first PR, so please let me know if there's anything wrong!
> Delete unnecessary code

- src/main/java/oss/fosslight/common/Url.java
- src/main/java/oss/fosslight/controller/ProjectController.java
src/main/oss/fosslight /common/Url.java
rename URL from OSS_VERIONS to OSS_VERSIONS ,
IDENTIFIATION_THIRD to IDENTIFICATION_THIRD and
IDENTIFICAITON_GRID_POST to IDENTIFICATION_GRID_POST
**AS-IS**
```java
public static final String OSS_VERIONS = PATH + "/getOssVersions";
public static final String IDENTIFIATION_THIRD = PATH + "/identificationThird";
public static final String IDENTIFICAITON_GRID_POST = PATH + "/identificationGridPost";
```
**TO-BE**
```java
public static final String OSS_VERSIONS = PATH + "/getOssVersions";
public static final String IDENTIFICATION_THIRD = PATH + "/identificationThird";
public static final String IDENTIFICATION_GRID_POST = PATH + "/identificationGridPost";
```
> Fix a typo at Url

- src/main/java/oss/fosslight/common/Url.java
- src/main/java/oss/fosslight/controller/OssController.java
src/main/oss/fosslight /common/Url.java
rename URL from DELTE_COMMENT
to DELETE_COMMENT
> Fix a typo from DELTE_COMMENT to DELETE_COMMENT

- .gitignore
- Register gitignore for auto-generated files
- related issue : https://github.com/fosslight/fosslight/issues/871
> Register gitignore for auto-generated files

- src/main/java/oss/fosslight/domain/CoMailManager.java
- src/main/java/oss/fosslight/util/PdfUtil.java
- src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
Signed-off-by: MyunghyunNero <mh1kim0910@gmail.com>
When the Project -> Identification stage is confirmed, 
the review report (PDF) is attached to the email and sent.
> Add Attach Pdf to Email

- src/main/java/oss/fosslight/controller/VerificationController.java
- src/main/resources/messages/message_en.properties
- src/main/resources/messages/message_ko.properties
- src/main/webapp/WEB-INF/views/admin/project/verification-js.jsp
- #881
Show a pop-up message when an unsupported file extension is uploaded in the Packaging tab.
Supported file extensions: System > Code Management > Code No: 120 > Code Detail: 16
- English 
- Korea
> Block unsupported file extensions in the packaging tab

- src/main/resources/oss/fosslight/repository/PartnerMapper.xml
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
- src/main/webapp/WEB-INF/views/admin/configuration/AJAX/searchConditionArea.jsp
- src/main/webapp/WEB-INF/views/admin/partner/list-js.jsp
- src/main/webapp/WEB-INF/views/admin/partner/list.jsp
- src/main/webapp/WEB-INF/views/admin/project/list-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/list.jsp
This PR add watcher feature to  **#817**
There is no watcher box in search box.
User can search watchers using search box
> Project part
https://github.com/fosslight/fosslight/assets/81344634/3abebd9f-4f6d-4889-b619-832da458c425
> Partner part
https://github.com/fosslight/fosslight/assets/81344634/1366148d-b7e9-4283-83cc-87978a5e27c9
> I added 3 data to show how _search_ works.
https://github.com/fosslight/fosslight/assets/81344634/de90a66f-ded0-4b93-be71-99c2f26394a6
When we search, we need to include the watcher and import all satisfied projects from the DB. To do so, a query statement was needed to import all the projects in question from the DB. Therefore, we added code to ProjectMapper.xml to import the query statement including the watcher item.
I added watcher box here. We can get …
> Added watcher search box in Project List, 3rd Party List

- src/main/resources/static/css/commonIframe.css
- src/main/webapp/WEB-INF/views/admin/oss/edit-js.jsp
- src/main/webapp/WEB-INF/views/admin/oss/edit.jsp
Added nick icon for newly added nicknames.
(I used the nick icon because there was no new icon, so please check it.)
closed: #882
> OSS > add > new icon for newly added nicknames

- src/main/webapp/WEB-INF/views/admin/project/bomCompare-js.jsp
Check two projects in the project list and click BOM Compare
1. AS-IS: With two project ids entered, you need to press the search button again to see the BOM Compare result.
2. TO-BE: When two project ids are entered and the Search button is clicked, the BOM Compare tab appears.
close #875
> Modify to do not have to press the search button

- src/main/resources/oss/fosslight/repository/OssMapper.xml
- src/main/webapp/WEB-INF/views/admin/configuration/AJAX/searchConditionArea.jsp
- src/main/webapp/WEB-INF/views/admin/oss/list.jsp
closes #939 
Add search condition in OSS List. 
Now, a user can search the OSS List by more than the vulnerability(>=) condition. And in the User Settings tab, the user can set user settings with vulnerability.
- Add input tag in 2 JSP file( admin/oss/list.jsp and searchConditionArea.jsp)
```
<label>Vulnerability (>=)</label>
<input name="cvssScore" type="text" value="${searchBean.cvssScore}" style="width:230px"/>
```
<br>
- Add search query in OSSMapper.xml
```
<if test="!@oss.fosslight.util.StringUtil@isEmpty(cvssScore)">
AND CAST(T1.CVSS_SCORE AS FLOAT ) >= CAST(#{cvssScore} AS FLOAT )
</if>
```
As Is :
<br>
To Be :
<br>
> Add vulnerability search to OSS List

- RELEASE_NOTES.md
- docs/RELEASE_NOTES_kor.md
> Update version to v1.6.1

- src/main/java/oss/fosslight/api/controller/v1/ApiSelfCheckController.java
Closes #919 
> An early-return pattern is when a function or method quickly returns a result based on a condition and finishes executing its logic.
I found nested conditions in [/api/v1/ApiSelfCheckController/](https://github.com/fosslight/fosslight/blob/212cca8a80de4957378193dd88b18b98430487eb/src/main/java/oss/fosslight/api/controller/v1/ApiSelfCheckController.java#L135-L225)
Nested conditions can cause poor readability, maintenance difficulties, difficulty understanding logic flow, and testing difficulties.
I think early-return can solve these problems.
**AS-IS**
```java
if (searchFlag) {
if (ossReport != null) {
// …
} else {
return responseService.getFailResult(CoConstDef.CD_OPEN_API_PARAMETER_ERROR_MESSAGE
, CoCodeManager.getCodeString(CoConstDef.CD_OPEN_API_MESSAGE, …
```
> Use early return pattern to avoid nested conditions

- .github/workflows/release-publish.yml
- build.gradle
- docker-compose.yml
* Change the method of building an image from Dockerfile to Jib.
* Modify the workflow from building an image with Docker and then pushing it to building and pushing with Jib.
* Modify the Docker Compose file.
```
./gradlew jibDockerBuild --image=fosslight/fosslight
```
> Build docker image with Jib

- .github/workflows/release-publish.yml
- Dockerfile
- build.gradle
- docker-compose.yml
- Replace docker base image from adopt to temulin.
- Build docker image with Jib.
> Update docker-related files

- RELEASE_NOTES.md
- docs/RELEASE_NOTES_kor.md
> Update release note (v1.6.1)

- CHANGELOG.md
- LICENSES/LicenseRef-3rd_party_licenses.txt
- RELEASE_NOTES.md
- src/main/java/oss/fosslight/common/CommonFunction.java
- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/java/oss/fosslight/service/impl/OssServiceImpl.java
- src/main/java/oss/fosslight/service/impl/SelfCheckServiceImpl.java
- src/main/java/oss/fosslight/util/ExcelDownLoadUtil.java
- src/main/java/oss/fosslight/util/PdfUtil.java
- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
- src/main/resources/static/css/commonIframe.css
- src/main/resources/static/js/basic.js
- src/main/resources/template/notice/selfcheck_notice.html
- src/main/webapp/WEB-INF/views/admin/oss/checkOssNamepopup.jsp
- src/main/webapp/WEB-INF/views/admin/project/bin-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/bom-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/dep-js.jsp
- src/main/webapp/WEB-INF/views/admin/project/identification.jsp
- src/main/webapp/WEB-INF/views/admin/project/src-js.jsp
- src/main/webapp/WEB-INF/views/admin/selfCheck/edit-js.jsp
- New Feature
- Help Message is added (Role of Creator & Reviewer, How to use FOSSLight)
- Bug Fix
- In Self-check, null license is generated.
- Modify notice template css in Self-Check.
- Bug fix where the loaded list only shows up to 20 items and is no longer displayed in Project > Identification.
- Bug fix where warning message disappears when ID is clicked in BOM tab.
- Bug fix where remove duplicates of rows with the same oss name, version, license, and copyright in OSS Notice of self-check.
- Bug fix where clicking "confirm" button, a success pop up appears even if there is a warning message in bom tab.
- Bug fix where saving the oss table loaded in the 3rd party tab.
- Bug fix where  a warning message is added to the license in case of a dual license when clicking Bulk Edit button. …
> Help Message is added (Role of Creator & Reviewer, How to use FOSSLight)

- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
Bug fix where modified comments are not saved in the security tab.
> Bug fix where modified comments are not saved in the security tab.

- src/main/java/oss/fosslight/controller/CycloneDXDownloadController.java
- src/main/java/oss/fosslight/service/impl/ProjectServiceImpl.java
- src/main/java/oss/fosslight/util/ExcelUtil.java
- src/main/webapp/WEB-INF/views/admin/project/common-js.jsp
- Bug fix where removing empty space when uploading report file and loading data into oss table.
- Bug fix where downloading CycloneDX report file.
> Bug fix where removing empty space when uploading report file and loading data into oss table.

- src/main/resources/static/css/commonIframe.css
Add CSS Style for clear_search_form button
> Add CSS for clear button

- .github/workflows/release-publish.yml
- build.gradle
Fix broken images by reverting a jib migration(#996). Also add `release.edited` to the GHA trigger and update some dependencies.
cc. @hyeinlee00
Fixes https://github.com/fosslight/fosslight/issues/1026#issuecomment-1962232821
> Fix broken images by reverting a jib migration

- src/main/java/oss/fosslight/common/Url.java
Add api/v1/prj_security_export_json URL to export security tab Export total list
> Add Api for Export Security As Jason

- build.gradle
Update build.gradle version to 2.0.0.pre-release
> Update build.gradle version

- src/main/java/oss/fosslight/util/PdfUtil.java
> Bug fix - null pointer exception in review report

- build.gradle
- src/main/resources/application.test.properties
- src/test/java/oss/fosslight/controller/LiteSelfCheckTest.java
- src/test/java/oss/fosslight/controller/OssControllerTest.java
- src/test/java/oss/fosslight/controller/PackingRequestTest.java
- src/test/java/oss/fosslight/controller/ProjectControllerIntegrationTest.java
- src/test/java/oss/fosslight/controller/ProjectIdentificationRequestReviewIntegrationTest.java
- src/test/java/oss/fosslight/controller/ProjectIdentificationReviewConfirmIntegrationTest.java
- src/test/java/oss/fosslight/controller/SelfCheckControllerIntegrationTest.java
update unit test for hub 2.0.0
security config is changed in hub 2.0.0, so test codes also need to be updated.
> Update unit test for hub 2.0.0

- src/main/java/oss/fosslight/service/impl/ApiProjectServiceImpl.java
Modify to allow uploading empty file in upload report api
Make uploading files by api work same as uploading files in UI
> Modify report upload api to upload empty file

- migration/migration/scripts/20240724045922_update_v2.0.0.pre-release_version_oss_components_table.sql
Add missing columns, TLSH and CHEKC_SUM, in OSS Components table
> Added migration script for bug fixes for higher versions of v2.0.0.pre-release

- src/main/webapp/WEB-INF/views/admin/oss/checkOssLicensepopup.jsp
fix incorrect external service configuration check logic in checkOssLicensepopup
> fix external service status message in checkOssLicensepopup

- .github/workflows/pull-request.yml
Docker compose command is changed from 'docker-compose' to 'docker compose'
[migration guide docker compose v2](https://docs.docker.com/compose/migrate/)
> Modify docker compose command in Github Action

- db/initdb.d/fosslight_create.sql
As requested by one of maintainers,
Changed Character-set and Collate for NVD_CVE_V3 to utf8mb4 from utf8
> [DEV] Changed Character-set and Collate for NVD_CVE_V3 to utf8mb4 from utf8

- db/initdb.d/fosslight_create.sql
As requested by one of maintainer,
Changed Character-set and Collate for NVD_CVE_V3 to utf8mb4 from utf8
> [v1.6.4] Changed Character-set and Collate for NVD_CVE_V3 to utf8mb4 from utf8

- db/initdb.d/fosslight_create.sql
- src/main/resources/application.properties
Changed the path of verify executable to relative path
> [V1.6.4] Changed the path of verify executable to relative path

- db/initdb.d/fosslight_create.sql
- src/main/resources/application.properties
[DEV] Changed the path of verify executable to relative path
> [DEV] Changed the path of verify executable to relative path

- src/main/java/oss/fosslight/common/Url.java
Add security/json-data api in API v2
> Add get an api to get security json data to API V2

- src/main/resources/oss/fosslight/repository/ProjectMapper.xml
Fix identification confirm function
> Fix identification confirm function

- RELEASE_NOTES.md
- build.gradle
- docs/RELEASE_NOTES_kor.md
- src/main/java/oss/fosslight/controller/ProjectController.java
- src/main/java/oss/fosslight/service/impl/VerificationServiceImpl.java
- src/main/resources/ehcache.xml
- src/main/resources/messages/message_en.properties
- src/main/resources/messages/message_ko.properties
- src/main/resources/templates/fragments/common-script.html
- src/main/resources/templates/fragments/default-script.html
- src/main/resources/templates/fragments/detail-script.html
- src/main/resources/templates/partner/edit-header.html
- src/main/resources/templates/partner/edit-script.html
- src/main/resources/templates/partner/list-header.html
- src/main/resources/templates/project/identification-header.html
- src/main/resources/templates/project/list-header.html
- src/main/resources/templates/project/project-edit_script.html
- src/main/resources/templates/project/security-header.html
- src/main/resources/templates/project/verification-header.html
- src/main/resources/templates/selfCheck/edit-header.html
- src/main/resources/templates/selfCheck/list-header.html
- src/main/resources/templates/system/configuration-header.html
- src/main/resources/templates/vulnerability/list-header.html
Hotfix for version 2.0.0
Implemented due to the discontinuation of CDN support for jqgrid.
> Release version 2.0.1

- CHANGELOG.md
- build.gradle
- src/main/java/oss/fosslight/util/TlshUtil.java
Update build.gradle version as 2.1.1
> Update build.gradle version 2.1.1
